# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.models.model_routing import ModelRouting

class TestModelRouting(unittest.TestCase):
    """ModelRouting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelRouting:
        """Test ModelRouting
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelRouting`
        """
        model = ModelRouting()
        if include_optional:
            return ModelRouting(
                kind = 'managed',
                provider_secret_id = '',
                default_model = beater_client.models.model_ref.ModelRef(
                    name = '', 
                    provider = '', )
            )
        else:
            return ModelRouting(
                kind = 'managed',
                provider_secret_id = '',
                default_model = beater_client.models.model_ref.ModelRef(
                    name = '', 
                    provider = '', ),
        )
        """

    def testModelRouting(self):
        """Test ModelRouting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
