# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.models.gateway_outcome import GatewayOutcome

class TestGatewayOutcome(unittest.TestCase):
    """GatewayOutcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayOutcome:
        """Test GatewayOutcome
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayOutcome`
        """
        model = GatewayOutcome()
        if include_optional:
            return GatewayOutcome(
                attempts = 0,
                cached = True,
                cost = beater_client.models.money.Money(
                    amount_micros = 56, 
                    currency = 'USD', ),
                model = beater_client.models.model_ref.ModelRef(
                    name = '', 
                    provider = '', ),
                provider = '',
                request_hash = '',
                response = beater_client.models.chat_completion_response.ChatCompletionResponse(
                    choices = [
                        beater_client.models.chat_completion_choice.ChatCompletionChoice(
                            finish_reason = '', 
                            index = 0, 
                            message = beater_client.models.chat_message.ChatMessage(
                                content = '', 
                                role = '', ), )
                        ], 
                    created = 56, 
                    id = '', 
                    model = '', 
                    object = '', 
                    usage = beater_client.models.chat_completion_usage.ChatCompletionUsage(
                        completion_tokens = 0, 
                        prompt_tokens = 0, 
                        total_tokens = 0, ), ),
                tokens = beater_client.models.token_counts.TokenCounts(
                    cache_read = 0, 
                    input = 0, 
                    output = 0, 
                    reasoning = 0, )
            )
        else:
            return GatewayOutcome(
                attempts = 0,
                cached = True,
                cost = beater_client.models.money.Money(
                    amount_micros = 56, 
                    currency = 'USD', ),
                model = beater_client.models.model_ref.ModelRef(
                    name = '', 
                    provider = '', ),
                provider = '',
                request_hash = '',
                response = beater_client.models.chat_completion_response.ChatCompletionResponse(
                    choices = [
                        beater_client.models.chat_completion_choice.ChatCompletionChoice(
                            finish_reason = '', 
                            index = 0, 
                            message = beater_client.models.chat_message.ChatMessage(
                                content = '', 
                                role = '', ), )
                        ], 
                    created = 56, 
                    id = '', 
                    model = '', 
                    object = '', 
                    usage = beater_client.models.chat_completion_usage.ChatCompletionUsage(
                        completion_tokens = 0, 
                        prompt_tokens = 0, 
                        total_tokens = 0, ), ),
                tokens = beater_client.models.token_counts.TokenCounts(
                    cache_read = 0, 
                    input = 0, 
                    output = 0, 
                    reasoning = 0, ),
        )
        """

    def testGatewayOutcome(self):
        """Test GatewayOutcome"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
