<?php
/**
 * ArchivedSpanRow
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;

use \ArrayAccess;
use \Beater\Client\ObjectSerializer;

/**
 * ArchivedSpanRow Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ArchivedSpanRow implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ArchivedSpanRow';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attributes_json' => 'string',
        'cost_amount_micros' => 'string',
        'cost_currency' => 'string',
        'end_time' => 'string',
        'environment_id' => 'string',
        'input_tokens' => 'string',
        'input_uri' => 'string',
        'kind' => 'string',
        'model_name' => 'string',
        'model_provider' => 'string',
        'name' => 'string',
        'output_tokens' => 'string',
        'output_uri' => 'string',
        'parent_span_id' => 'string',
        'project_id' => 'string',
        'raw_uri' => 'string',
        'reasoning_tokens' => 'string',
        'seq' => 'int',
        'span_id' => 'string',
        'start_time' => 'string',
        'status' => 'string',
        'tenant_id' => 'string',
        'trace_id' => 'string',
        'unmapped_json' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attributes_json' => null,
        'cost_amount_micros' => null,
        'cost_currency' => null,
        'end_time' => null,
        'environment_id' => null,
        'input_tokens' => null,
        'input_uri' => null,
        'kind' => null,
        'model_name' => null,
        'model_provider' => null,
        'name' => null,
        'output_tokens' => null,
        'output_uri' => null,
        'parent_span_id' => null,
        'project_id' => null,
        'raw_uri' => null,
        'reasoning_tokens' => null,
        'seq' => 'int64',
        'span_id' => null,
        'start_time' => null,
        'status' => null,
        'tenant_id' => null,
        'trace_id' => null,
        'unmapped_json' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attributes_json' => false,
        'cost_amount_micros' => true,
        'cost_currency' => true,
        'end_time' => true,
        'environment_id' => false,
        'input_tokens' => true,
        'input_uri' => true,
        'kind' => false,
        'model_name' => true,
        'model_provider' => true,
        'name' => false,
        'output_tokens' => true,
        'output_uri' => true,
        'parent_span_id' => true,
        'project_id' => false,
        'raw_uri' => false,
        'reasoning_tokens' => true,
        'seq' => false,
        'span_id' => false,
        'start_time' => false,
        'status' => false,
        'tenant_id' => false,
        'trace_id' => false,
        'unmapped_json' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attributes_json' => 'attributes_json',
        'cost_amount_micros' => 'cost_amount_micros',
        'cost_currency' => 'cost_currency',
        'end_time' => 'end_time',
        'environment_id' => 'environment_id',
        'input_tokens' => 'input_tokens',
        'input_uri' => 'input_uri',
        'kind' => 'kind',
        'model_name' => 'model_name',
        'model_provider' => 'model_provider',
        'name' => 'name',
        'output_tokens' => 'output_tokens',
        'output_uri' => 'output_uri',
        'parent_span_id' => 'parent_span_id',
        'project_id' => 'project_id',
        'raw_uri' => 'raw_uri',
        'reasoning_tokens' => 'reasoning_tokens',
        'seq' => 'seq',
        'span_id' => 'span_id',
        'start_time' => 'start_time',
        'status' => 'status',
        'tenant_id' => 'tenant_id',
        'trace_id' => 'trace_id',
        'unmapped_json' => 'unmapped_json'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attributes_json' => 'setAttributesJson',
        'cost_amount_micros' => 'setCostAmountMicros',
        'cost_currency' => 'setCostCurrency',
        'end_time' => 'setEndTime',
        'environment_id' => 'setEnvironmentId',
        'input_tokens' => 'setInputTokens',
        'input_uri' => 'setInputUri',
        'kind' => 'setKind',
        'model_name' => 'setModelName',
        'model_provider' => 'setModelProvider',
        'name' => 'setName',
        'output_tokens' => 'setOutputTokens',
        'output_uri' => 'setOutputUri',
        'parent_span_id' => 'setParentSpanId',
        'project_id' => 'setProjectId',
        'raw_uri' => 'setRawUri',
        'reasoning_tokens' => 'setReasoningTokens',
        'seq' => 'setSeq',
        'span_id' => 'setSpanId',
        'start_time' => 'setStartTime',
        'status' => 'setStatus',
        'tenant_id' => 'setTenantId',
        'trace_id' => 'setTraceId',
        'unmapped_json' => 'setUnmappedJson'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attributes_json' => 'getAttributesJson',
        'cost_amount_micros' => 'getCostAmountMicros',
        'cost_currency' => 'getCostCurrency',
        'end_time' => 'getEndTime',
        'environment_id' => 'getEnvironmentId',
        'input_tokens' => 'getInputTokens',
        'input_uri' => 'getInputUri',
        'kind' => 'getKind',
        'model_name' => 'getModelName',
        'model_provider' => 'getModelProvider',
        'name' => 'getName',
        'output_tokens' => 'getOutputTokens',
        'output_uri' => 'getOutputUri',
        'parent_span_id' => 'getParentSpanId',
        'project_id' => 'getProjectId',
        'raw_uri' => 'getRawUri',
        'reasoning_tokens' => 'getReasoningTokens',
        'seq' => 'getSeq',
        'span_id' => 'getSpanId',
        'start_time' => 'getStartTime',
        'status' => 'getStatus',
        'tenant_id' => 'getTenantId',
        'trace_id' => 'getTraceId',
        'unmapped_json' => 'getUnmappedJson'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attributes_json', $data ?? [], null);
        $this->setIfExists('cost_amount_micros', $data ?? [], null);
        $this->setIfExists('cost_currency', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('environment_id', $data ?? [], null);
        $this->setIfExists('input_tokens', $data ?? [], null);
        $this->setIfExists('input_uri', $data ?? [], null);
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('model_name', $data ?? [], null);
        $this->setIfExists('model_provider', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('output_tokens', $data ?? [], null);
        $this->setIfExists('output_uri', $data ?? [], null);
        $this->setIfExists('parent_span_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('raw_uri', $data ?? [], null);
        $this->setIfExists('reasoning_tokens', $data ?? [], null);
        $this->setIfExists('seq', $data ?? [], null);
        $this->setIfExists('span_id', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('trace_id', $data ?? [], null);
        $this->setIfExists('unmapped_json', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['attributes_json'] === null) {
            $invalidProperties[] = "'attributes_json' can't be null";
        }
        if ($this->container['environment_id'] === null) {
            $invalidProperties[] = "'environment_id' can't be null";
        }
        if ($this->container['kind'] === null) {
            $invalidProperties[] = "'kind' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['project_id'] === null) {
            $invalidProperties[] = "'project_id' can't be null";
        }
        if ($this->container['raw_uri'] === null) {
            $invalidProperties[] = "'raw_uri' can't be null";
        }
        if ($this->container['seq'] === null) {
            $invalidProperties[] = "'seq' can't be null";
        }
        if (($this->container['seq'] < 0)) {
            $invalidProperties[] = "invalid value for 'seq', must be bigger than or equal to 0.";
        }

        if ($this->container['span_id'] === null) {
            $invalidProperties[] = "'span_id' can't be null";
        }
        if ($this->container['start_time'] === null) {
            $invalidProperties[] = "'start_time' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if ($this->container['trace_id'] === null) {
            $invalidProperties[] = "'trace_id' can't be null";
        }
        if ($this->container['unmapped_json'] === null) {
            $invalidProperties[] = "'unmapped_json' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attributes_json
     *
     * @return string
     */
    public function getAttributesJson()
    {
        return $this->container['attributes_json'];
    }

    /**
     * Sets attributes_json
     *
     * @param string $attributes_json attributes_json
     *
     * @return self
     */
    public function setAttributesJson($attributes_json)
    {
        if (is_null($attributes_json)) {
            throw new \InvalidArgumentException('non-nullable attributes_json cannot be null');
        }
        $this->container['attributes_json'] = $attributes_json;

        return $this;
    }

    /**
     * Gets cost_amount_micros
     *
     * @return string|null
     */
    public function getCostAmountMicros()
    {
        return $this->container['cost_amount_micros'];
    }

    /**
     * Sets cost_amount_micros
     *
     * @param string|null $cost_amount_micros cost_amount_micros
     *
     * @return self
     */
    public function setCostAmountMicros($cost_amount_micros)
    {
        if (is_null($cost_amount_micros)) {
            array_push($this->openAPINullablesSetToNull, 'cost_amount_micros');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cost_amount_micros', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cost_amount_micros'] = $cost_amount_micros;

        return $this;
    }

    /**
     * Gets cost_currency
     *
     * @return string|null
     */
    public function getCostCurrency()
    {
        return $this->container['cost_currency'];
    }

    /**
     * Sets cost_currency
     *
     * @param string|null $cost_currency cost_currency
     *
     * @return self
     */
    public function setCostCurrency($cost_currency)
    {
        if (is_null($cost_currency)) {
            array_push($this->openAPINullablesSetToNull, 'cost_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cost_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cost_currency'] = $cost_currency;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return string|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param string|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            array_push($this->openAPINullablesSetToNull, 'end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets environment_id
     *
     * @return string
     */
    public function getEnvironmentId()
    {
        return $this->container['environment_id'];
    }

    /**
     * Sets environment_id
     *
     * @param string $environment_id environment_id
     *
     * @return self
     */
    public function setEnvironmentId($environment_id)
    {
        if (is_null($environment_id)) {
            throw new \InvalidArgumentException('non-nullable environment_id cannot be null');
        }
        $this->container['environment_id'] = $environment_id;

        return $this;
    }

    /**
     * Gets input_tokens
     *
     * @return string|null
     */
    public function getInputTokens()
    {
        return $this->container['input_tokens'];
    }

    /**
     * Sets input_tokens
     *
     * @param string|null $input_tokens input_tokens
     *
     * @return self
     */
    public function setInputTokens($input_tokens)
    {
        if (is_null($input_tokens)) {
            array_push($this->openAPINullablesSetToNull, 'input_tokens');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('input_tokens', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['input_tokens'] = $input_tokens;

        return $this;
    }

    /**
     * Gets input_uri
     *
     * @return string|null
     */
    public function getInputUri()
    {
        return $this->container['input_uri'];
    }

    /**
     * Sets input_uri
     *
     * @param string|null $input_uri input_uri
     *
     * @return self
     */
    public function setInputUri($input_uri)
    {
        if (is_null($input_uri)) {
            array_push($this->openAPINullablesSetToNull, 'input_uri');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('input_uri', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['input_uri'] = $input_uri;

        return $this;
    }

    /**
     * Gets kind
     *
     * @return string
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string $kind kind
     *
     * @return self
     */
    public function setKind($kind)
    {
        if (is_null($kind)) {
            throw new \InvalidArgumentException('non-nullable kind cannot be null');
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets model_name
     *
     * @return string|null
     */
    public function getModelName()
    {
        return $this->container['model_name'];
    }

    /**
     * Sets model_name
     *
     * @param string|null $model_name model_name
     *
     * @return self
     */
    public function setModelName($model_name)
    {
        if (is_null($model_name)) {
            array_push($this->openAPINullablesSetToNull, 'model_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('model_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['model_name'] = $model_name;

        return $this;
    }

    /**
     * Gets model_provider
     *
     * @return string|null
     */
    public function getModelProvider()
    {
        return $this->container['model_provider'];
    }

    /**
     * Sets model_provider
     *
     * @param string|null $model_provider model_provider
     *
     * @return self
     */
    public function setModelProvider($model_provider)
    {
        if (is_null($model_provider)) {
            array_push($this->openAPINullablesSetToNull, 'model_provider');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('model_provider', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['model_provider'] = $model_provider;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets output_tokens
     *
     * @return string|null
     */
    public function getOutputTokens()
    {
        return $this->container['output_tokens'];
    }

    /**
     * Sets output_tokens
     *
     * @param string|null $output_tokens output_tokens
     *
     * @return self
     */
    public function setOutputTokens($output_tokens)
    {
        if (is_null($output_tokens)) {
            array_push($this->openAPINullablesSetToNull, 'output_tokens');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('output_tokens', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['output_tokens'] = $output_tokens;

        return $this;
    }

    /**
     * Gets output_uri
     *
     * @return string|null
     */
    public function getOutputUri()
    {
        return $this->container['output_uri'];
    }

    /**
     * Sets output_uri
     *
     * @param string|null $output_uri output_uri
     *
     * @return self
     */
    public function setOutputUri($output_uri)
    {
        if (is_null($output_uri)) {
            array_push($this->openAPINullablesSetToNull, 'output_uri');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('output_uri', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['output_uri'] = $output_uri;

        return $this;
    }

    /**
     * Gets parent_span_id
     *
     * @return string|null
     */
    public function getParentSpanId()
    {
        return $this->container['parent_span_id'];
    }

    /**
     * Sets parent_span_id
     *
     * @param string|null $parent_span_id parent_span_id
     *
     * @return self
     */
    public function setParentSpanId($parent_span_id)
    {
        if (is_null($parent_span_id)) {
            array_push($this->openAPINullablesSetToNull, 'parent_span_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parent_span_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['parent_span_id'] = $parent_span_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets raw_uri
     *
     * @return string
     */
    public function getRawUri()
    {
        return $this->container['raw_uri'];
    }

    /**
     * Sets raw_uri
     *
     * @param string $raw_uri raw_uri
     *
     * @return self
     */
    public function setRawUri($raw_uri)
    {
        if (is_null($raw_uri)) {
            throw new \InvalidArgumentException('non-nullable raw_uri cannot be null');
        }
        $this->container['raw_uri'] = $raw_uri;

        return $this;
    }

    /**
     * Gets reasoning_tokens
     *
     * @return string|null
     */
    public function getReasoningTokens()
    {
        return $this->container['reasoning_tokens'];
    }

    /**
     * Sets reasoning_tokens
     *
     * @param string|null $reasoning_tokens reasoning_tokens
     *
     * @return self
     */
    public function setReasoningTokens($reasoning_tokens)
    {
        if (is_null($reasoning_tokens)) {
            array_push($this->openAPINullablesSetToNull, 'reasoning_tokens');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reasoning_tokens', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reasoning_tokens'] = $reasoning_tokens;

        return $this;
    }

    /**
     * Gets seq
     *
     * @return int
     */
    public function getSeq()
    {
        return $this->container['seq'];
    }

    /**
     * Sets seq
     *
     * @param int $seq seq
     *
     * @return self
     */
    public function setSeq($seq)
    {
        if (is_null($seq)) {
            throw new \InvalidArgumentException('non-nullable seq cannot be null');
        }

        if (($seq < 0)) {
            throw new \InvalidArgumentException('invalid value for $seq when calling ArchivedSpanRow., must be bigger than or equal to 0.');
        }

        $this->container['seq'] = $seq;

        return $this;
    }

    /**
     * Gets span_id
     *
     * @return string
     */
    public function getSpanId()
    {
        return $this->container['span_id'];
    }

    /**
     * Sets span_id
     *
     * @param string $span_id span_id
     *
     * @return self
     */
    public function setSpanId($span_id)
    {
        if (is_null($span_id)) {
            throw new \InvalidArgumentException('non-nullable span_id cannot be null');
        }
        $this->container['span_id'] = $span_id;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return string
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param string $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets trace_id
     *
     * @return string
     */
    public function getTraceId()
    {
        return $this->container['trace_id'];
    }

    /**
     * Sets trace_id
     *
     * @param string $trace_id trace_id
     *
     * @return self
     */
    public function setTraceId($trace_id)
    {
        if (is_null($trace_id)) {
            throw new \InvalidArgumentException('non-nullable trace_id cannot be null');
        }
        $this->container['trace_id'] = $trace_id;

        return $this;
    }

    /**
     * Gets unmapped_json
     *
     * @return string
     */
    public function getUnmappedJson()
    {
        return $this->container['unmapped_json'];
    }

    /**
     * Sets unmapped_json
     *
     * @param string $unmapped_json unmapped_json
     *
     * @return self
     */
    public function setUnmappedJson($unmapped_json)
    {
        if (is_null($unmapped_json)) {
            throw new \InvalidArgumentException('non-nullable unmapped_json cannot be null');
        }
        $this->container['unmapped_json'] = $unmapped_json;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
