<?php
/**
 * AuditAction
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;
use \Beater\Client\ObjectSerializer;

/**
 * AuditAction Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditAction
{
    /**
     * Possible values of this enum
     */
    public const PII_UNMASK = 'pii_unmask';

    public const API_KEY_CREATE = 'api_key_create';

    public const API_KEY_REVOKE = 'api_key_revoke';

    public const PROVIDER_SECRET_CREATE = 'provider_secret_create';

    public const PROVIDER_SECRET_REVOKE = 'provider_secret_revoke';

    public const CONNECTOR_TOOL_INVOKE = 'connector_tool_invoke';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PII_UNMASK,
            self::API_KEY_CREATE,
            self::API_KEY_REVOKE,
            self::PROVIDER_SECRET_CREATE,
            self::PROVIDER_SECRET_REVOKE,
            self::CONNECTOR_TOOL_INVOKE
        ];
    }
}
