<?php
/**
 * CalibrationItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;

use \ArrayAccess;
use \Beater\Client\ObjectSerializer;

/**
 * CalibrationItem Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CalibrationItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CalibrationItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'agreed' => 'bool',
        'dataset_case_id' => 'string',
        'evidence' => 'mixed',
        'human_label' => '\Beater\Client\Model\CalibrationLabel',
        'judge_label' => '\Beater\Client\Model\CalibrationLabel',
        'judge_result_label' => 'string',
        'judge_score' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'agreed' => null,
        'dataset_case_id' => null,
        'evidence' => null,
        'human_label' => null,
        'judge_label' => null,
        'judge_result_label' => null,
        'judge_score' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'agreed' => false,
        'dataset_case_id' => false,
        'evidence' => true,
        'human_label' => false,
        'judge_label' => false,
        'judge_result_label' => true,
        'judge_score' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'agreed' => 'agreed',
        'dataset_case_id' => 'dataset_case_id',
        'evidence' => 'evidence',
        'human_label' => 'human_label',
        'judge_label' => 'judge_label',
        'judge_result_label' => 'judge_result_label',
        'judge_score' => 'judge_score'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'agreed' => 'setAgreed',
        'dataset_case_id' => 'setDatasetCaseId',
        'evidence' => 'setEvidence',
        'human_label' => 'setHumanLabel',
        'judge_label' => 'setJudgeLabel',
        'judge_result_label' => 'setJudgeResultLabel',
        'judge_score' => 'setJudgeScore'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'agreed' => 'getAgreed',
        'dataset_case_id' => 'getDatasetCaseId',
        'evidence' => 'getEvidence',
        'human_label' => 'getHumanLabel',
        'judge_label' => 'getJudgeLabel',
        'judge_result_label' => 'getJudgeResultLabel',
        'judge_score' => 'getJudgeScore'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('agreed', $data ?? [], null);
        $this->setIfExists('dataset_case_id', $data ?? [], null);
        $this->setIfExists('evidence', $data ?? [], null);
        $this->setIfExists('human_label', $data ?? [], null);
        $this->setIfExists('judge_label', $data ?? [], null);
        $this->setIfExists('judge_result_label', $data ?? [], null);
        $this->setIfExists('judge_score', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['agreed'] === null) {
            $invalidProperties[] = "'agreed' can't be null";
        }
        if ($this->container['dataset_case_id'] === null) {
            $invalidProperties[] = "'dataset_case_id' can't be null";
        }
        if ($this->container['evidence'] === null) {
            $invalidProperties[] = "'evidence' can't be null";
        }
        if ($this->container['human_label'] === null) {
            $invalidProperties[] = "'human_label' can't be null";
        }
        if ($this->container['judge_label'] === null) {
            $invalidProperties[] = "'judge_label' can't be null";
        }
        if ($this->container['judge_score'] === null) {
            $invalidProperties[] = "'judge_score' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets agreed
     *
     * @return bool
     */
    public function getAgreed()
    {
        return $this->container['agreed'];
    }

    /**
     * Sets agreed
     *
     * @param bool $agreed agreed
     *
     * @return self
     */
    public function setAgreed($agreed)
    {
        if (is_null($agreed)) {
            throw new \InvalidArgumentException('non-nullable agreed cannot be null');
        }
        $this->container['agreed'] = $agreed;

        return $this;
    }

    /**
     * Gets dataset_case_id
     *
     * @return string
     */
    public function getDatasetCaseId()
    {
        return $this->container['dataset_case_id'];
    }

    /**
     * Sets dataset_case_id
     *
     * @param string $dataset_case_id dataset_case_id
     *
     * @return self
     */
    public function setDatasetCaseId($dataset_case_id)
    {
        if (is_null($dataset_case_id)) {
            throw new \InvalidArgumentException('non-nullable dataset_case_id cannot be null');
        }
        $this->container['dataset_case_id'] = $dataset_case_id;

        return $this;
    }

    /**
     * Gets evidence
     *
     * @return mixed
     */
    public function getEvidence()
    {
        return $this->container['evidence'];
    }

    /**
     * Sets evidence
     *
     * @param mixed $evidence evidence
     *
     * @return self
     */
    public function setEvidence($evidence)
    {
        if (is_null($evidence)) {
            array_push($this->openAPINullablesSetToNull, 'evidence');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('evidence', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['evidence'] = $evidence;

        return $this;
    }

    /**
     * Gets human_label
     *
     * @return \Beater\Client\Model\CalibrationLabel
     */
    public function getHumanLabel()
    {
        return $this->container['human_label'];
    }

    /**
     * Sets human_label
     *
     * @param \Beater\Client\Model\CalibrationLabel $human_label human_label
     *
     * @return self
     */
    public function setHumanLabel($human_label)
    {
        if (is_null($human_label)) {
            throw new \InvalidArgumentException('non-nullable human_label cannot be null');
        }
        $this->container['human_label'] = $human_label;

        return $this;
    }

    /**
     * Gets judge_label
     *
     * @return \Beater\Client\Model\CalibrationLabel
     */
    public function getJudgeLabel()
    {
        return $this->container['judge_label'];
    }

    /**
     * Sets judge_label
     *
     * @param \Beater\Client\Model\CalibrationLabel $judge_label judge_label
     *
     * @return self
     */
    public function setJudgeLabel($judge_label)
    {
        if (is_null($judge_label)) {
            throw new \InvalidArgumentException('non-nullable judge_label cannot be null');
        }
        $this->container['judge_label'] = $judge_label;

        return $this;
    }

    /**
     * Gets judge_result_label
     *
     * @return string|null
     */
    public function getJudgeResultLabel()
    {
        return $this->container['judge_result_label'];
    }

    /**
     * Sets judge_result_label
     *
     * @param string|null $judge_result_label judge_result_label
     *
     * @return self
     */
    public function setJudgeResultLabel($judge_result_label)
    {
        if (is_null($judge_result_label)) {
            array_push($this->openAPINullablesSetToNull, 'judge_result_label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('judge_result_label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['judge_result_label'] = $judge_result_label;

        return $this;
    }

    /**
     * Gets judge_score
     *
     * @return float
     */
    public function getJudgeScore()
    {
        return $this->container['judge_score'];
    }

    /**
     * Sets judge_score
     *
     * @param float $judge_score judge_score
     *
     * @return self
     */
    public function setJudgeScore($judge_score)
    {
        if (is_null($judge_score)) {
            throw new \InvalidArgumentException('non-nullable judge_score cannot be null');
        }
        $this->container['judge_score'] = $judge_score;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
