<?php
/**
 * CanonicalSpan
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;

use \ArrayAccess;
use \Beater\Client\ObjectSerializer;

/**
 * CanonicalSpan Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CanonicalSpan implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CanonicalSpan';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attributes' => 'array<string,mixed>',
        'cost' => '\Beater\Client\Model\Money',
        'end_time' => '\DateTime',
        'environment_id' => 'string',
        'input_ref' => '\Beater\Client\Model\ArtifactRef',
        'kind' => 'string',
        'model' => '\Beater\Client\Model\ModelRef',
        'name' => 'string',
        'normalizer_version' => 'string',
        'output_ref' => '\Beater\Client\Model\ArtifactRef',
        'parent_span_id' => 'string',
        'project_id' => 'string',
        'raw_ref' => '\Beater\Client\Model\ArtifactRef',
        'schema_version' => 'int',
        'seq' => 'int',
        'span_id' => 'string',
        'start_time' => '\DateTime',
        'status' => '\Beater\Client\Model\SpanStatus',
        'tenant_id' => 'string',
        'tokens' => '\Beater\Client\Model\TokenCounts',
        'trace_id' => 'string',
        'unmapped_attrs' => 'mixed'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attributes' => null,
        'cost' => null,
        'end_time' => 'date-time',
        'environment_id' => null,
        'input_ref' => null,
        'kind' => null,
        'model' => null,
        'name' => null,
        'normalizer_version' => null,
        'output_ref' => null,
        'parent_span_id' => null,
        'project_id' => null,
        'raw_ref' => null,
        'schema_version' => 'int32',
        'seq' => 'int64',
        'span_id' => null,
        'start_time' => 'date-time',
        'status' => null,
        'tenant_id' => null,
        'tokens' => null,
        'trace_id' => null,
        'unmapped_attrs' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attributes' => false,
        'cost' => true,
        'end_time' => true,
        'environment_id' => false,
        'input_ref' => true,
        'kind' => false,
        'model' => true,
        'name' => false,
        'normalizer_version' => false,
        'output_ref' => true,
        'parent_span_id' => false,
        'project_id' => false,
        'raw_ref' => false,
        'schema_version' => false,
        'seq' => false,
        'span_id' => false,
        'start_time' => false,
        'status' => false,
        'tenant_id' => false,
        'tokens' => true,
        'trace_id' => false,
        'unmapped_attrs' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attributes' => 'attributes',
        'cost' => 'cost',
        'end_time' => 'end_time',
        'environment_id' => 'environment_id',
        'input_ref' => 'input_ref',
        'kind' => 'kind',
        'model' => 'model',
        'name' => 'name',
        'normalizer_version' => 'normalizer_version',
        'output_ref' => 'output_ref',
        'parent_span_id' => 'parent_span_id',
        'project_id' => 'project_id',
        'raw_ref' => 'raw_ref',
        'schema_version' => 'schema_version',
        'seq' => 'seq',
        'span_id' => 'span_id',
        'start_time' => 'start_time',
        'status' => 'status',
        'tenant_id' => 'tenant_id',
        'tokens' => 'tokens',
        'trace_id' => 'trace_id',
        'unmapped_attrs' => 'unmapped_attrs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attributes' => 'setAttributes',
        'cost' => 'setCost',
        'end_time' => 'setEndTime',
        'environment_id' => 'setEnvironmentId',
        'input_ref' => 'setInputRef',
        'kind' => 'setKind',
        'model' => 'setModel',
        'name' => 'setName',
        'normalizer_version' => 'setNormalizerVersion',
        'output_ref' => 'setOutputRef',
        'parent_span_id' => 'setParentSpanId',
        'project_id' => 'setProjectId',
        'raw_ref' => 'setRawRef',
        'schema_version' => 'setSchemaVersion',
        'seq' => 'setSeq',
        'span_id' => 'setSpanId',
        'start_time' => 'setStartTime',
        'status' => 'setStatus',
        'tenant_id' => 'setTenantId',
        'tokens' => 'setTokens',
        'trace_id' => 'setTraceId',
        'unmapped_attrs' => 'setUnmappedAttrs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attributes' => 'getAttributes',
        'cost' => 'getCost',
        'end_time' => 'getEndTime',
        'environment_id' => 'getEnvironmentId',
        'input_ref' => 'getInputRef',
        'kind' => 'getKind',
        'model' => 'getModel',
        'name' => 'getName',
        'normalizer_version' => 'getNormalizerVersion',
        'output_ref' => 'getOutputRef',
        'parent_span_id' => 'getParentSpanId',
        'project_id' => 'getProjectId',
        'raw_ref' => 'getRawRef',
        'schema_version' => 'getSchemaVersion',
        'seq' => 'getSeq',
        'span_id' => 'getSpanId',
        'start_time' => 'getStartTime',
        'status' => 'getStatus',
        'tenant_id' => 'getTenantId',
        'tokens' => 'getTokens',
        'trace_id' => 'getTraceId',
        'unmapped_attrs' => 'getUnmappedAttrs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('cost', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('environment_id', $data ?? [], null);
        $this->setIfExists('input_ref', $data ?? [], null);
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('normalizer_version', $data ?? [], null);
        $this->setIfExists('output_ref', $data ?? [], null);
        $this->setIfExists('parent_span_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('raw_ref', $data ?? [], null);
        $this->setIfExists('schema_version', $data ?? [], null);
        $this->setIfExists('seq', $data ?? [], null);
        $this->setIfExists('span_id', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('tokens', $data ?? [], null);
        $this->setIfExists('trace_id', $data ?? [], null);
        $this->setIfExists('unmapped_attrs', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['attributes'] === null) {
            $invalidProperties[] = "'attributes' can't be null";
        }
        if ($this->container['environment_id'] === null) {
            $invalidProperties[] = "'environment_id' can't be null";
        }
        if ($this->container['kind'] === null) {
            $invalidProperties[] = "'kind' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['normalizer_version'] === null) {
            $invalidProperties[] = "'normalizer_version' can't be null";
        }
        if ($this->container['project_id'] === null) {
            $invalidProperties[] = "'project_id' can't be null";
        }
        if ($this->container['raw_ref'] === null) {
            $invalidProperties[] = "'raw_ref' can't be null";
        }
        if ($this->container['schema_version'] === null) {
            $invalidProperties[] = "'schema_version' can't be null";
        }
        if (($this->container['schema_version'] < 0)) {
            $invalidProperties[] = "invalid value for 'schema_version', must be bigger than or equal to 0.";
        }

        if ($this->container['seq'] === null) {
            $invalidProperties[] = "'seq' can't be null";
        }
        if (($this->container['seq'] < 0)) {
            $invalidProperties[] = "invalid value for 'seq', must be bigger than or equal to 0.";
        }

        if ($this->container['span_id'] === null) {
            $invalidProperties[] = "'span_id' can't be null";
        }
        if ($this->container['start_time'] === null) {
            $invalidProperties[] = "'start_time' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if ($this->container['trace_id'] === null) {
            $invalidProperties[] = "'trace_id' can't be null";
        }
        if ($this->container['unmapped_attrs'] === null) {
            $invalidProperties[] = "'unmapped_attrs' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attributes
     *
     * @return array<string,mixed>
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param array<string,mixed> $attributes attributes
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return \Beater\Client\Model\Money|null
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param \Beater\Client\Model\Money|null $cost cost
     *
     * @return self
     */
    public function setCost($cost)
    {
        if (is_null($cost)) {
            array_push($this->openAPINullablesSetToNull, 'cost');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cost', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return \DateTime|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param \DateTime|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            array_push($this->openAPINullablesSetToNull, 'end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets environment_id
     *
     * @return string
     */
    public function getEnvironmentId()
    {
        return $this->container['environment_id'];
    }

    /**
     * Sets environment_id
     *
     * @param string $environment_id environment_id
     *
     * @return self
     */
    public function setEnvironmentId($environment_id)
    {
        if (is_null($environment_id)) {
            throw new \InvalidArgumentException('non-nullable environment_id cannot be null');
        }
        $this->container['environment_id'] = $environment_id;

        return $this;
    }

    /**
     * Gets input_ref
     *
     * @return \Beater\Client\Model\ArtifactRef|null
     */
    public function getInputRef()
    {
        return $this->container['input_ref'];
    }

    /**
     * Sets input_ref
     *
     * @param \Beater\Client\Model\ArtifactRef|null $input_ref input_ref
     *
     * @return self
     */
    public function setInputRef($input_ref)
    {
        if (is_null($input_ref)) {
            array_push($this->openAPINullablesSetToNull, 'input_ref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('input_ref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['input_ref'] = $input_ref;

        return $this;
    }

    /**
     * Gets kind
     *
     * @return string
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string $kind Canonical agent span kind such as agent.run or llm.call
     *
     * @return self
     */
    public function setKind($kind)
    {
        if (is_null($kind)) {
            throw new \InvalidArgumentException('non-nullable kind cannot be null');
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets model
     *
     * @return \Beater\Client\Model\ModelRef|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param \Beater\Client\Model\ModelRef|null $model model
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            array_push($this->openAPINullablesSetToNull, 'model');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('model', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets normalizer_version
     *
     * @return string
     */
    public function getNormalizerVersion()
    {
        return $this->container['normalizer_version'];
    }

    /**
     * Sets normalizer_version
     *
     * @param string $normalizer_version normalizer_version
     *
     * @return self
     */
    public function setNormalizerVersion($normalizer_version)
    {
        if (is_null($normalizer_version)) {
            throw new \InvalidArgumentException('non-nullable normalizer_version cannot be null');
        }
        $this->container['normalizer_version'] = $normalizer_version;

        return $this;
    }

    /**
     * Gets output_ref
     *
     * @return \Beater\Client\Model\ArtifactRef|null
     */
    public function getOutputRef()
    {
        return $this->container['output_ref'];
    }

    /**
     * Sets output_ref
     *
     * @param \Beater\Client\Model\ArtifactRef|null $output_ref output_ref
     *
     * @return self
     */
    public function setOutputRef($output_ref)
    {
        if (is_null($output_ref)) {
            array_push($this->openAPINullablesSetToNull, 'output_ref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('output_ref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['output_ref'] = $output_ref;

        return $this;
    }

    /**
     * Gets parent_span_id
     *
     * @return string|null
     */
    public function getParentSpanId()
    {
        return $this->container['parent_span_id'];
    }

    /**
     * Sets parent_span_id
     *
     * @param string|null $parent_span_id parent_span_id
     *
     * @return self
     */
    public function setParentSpanId($parent_span_id)
    {
        if (is_null($parent_span_id)) {
            throw new \InvalidArgumentException('non-nullable parent_span_id cannot be null');
        }
        $this->container['parent_span_id'] = $parent_span_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets raw_ref
     *
     * @return \Beater\Client\Model\ArtifactRef
     */
    public function getRawRef()
    {
        return $this->container['raw_ref'];
    }

    /**
     * Sets raw_ref
     *
     * @param \Beater\Client\Model\ArtifactRef $raw_ref raw_ref
     *
     * @return self
     */
    public function setRawRef($raw_ref)
    {
        if (is_null($raw_ref)) {
            throw new \InvalidArgumentException('non-nullable raw_ref cannot be null');
        }
        $this->container['raw_ref'] = $raw_ref;

        return $this;
    }

    /**
     * Gets schema_version
     *
     * @return int
     */
    public function getSchemaVersion()
    {
        return $this->container['schema_version'];
    }

    /**
     * Sets schema_version
     *
     * @param int $schema_version schema_version
     *
     * @return self
     */
    public function setSchemaVersion($schema_version)
    {
        if (is_null($schema_version)) {
            throw new \InvalidArgumentException('non-nullable schema_version cannot be null');
        }

        if (($schema_version < 0)) {
            throw new \InvalidArgumentException('invalid value for $schema_version when calling CanonicalSpan., must be bigger than or equal to 0.');
        }

        $this->container['schema_version'] = $schema_version;

        return $this;
    }

    /**
     * Gets seq
     *
     * @return int
     */
    public function getSeq()
    {
        return $this->container['seq'];
    }

    /**
     * Sets seq
     *
     * @param int $seq seq
     *
     * @return self
     */
    public function setSeq($seq)
    {
        if (is_null($seq)) {
            throw new \InvalidArgumentException('non-nullable seq cannot be null');
        }

        if (($seq < 0)) {
            throw new \InvalidArgumentException('invalid value for $seq when calling CanonicalSpan., must be bigger than or equal to 0.');
        }

        $this->container['seq'] = $seq;

        return $this;
    }

    /**
     * Gets span_id
     *
     * @return string
     */
    public function getSpanId()
    {
        return $this->container['span_id'];
    }

    /**
     * Sets span_id
     *
     * @param string $span_id span_id
     *
     * @return self
     */
    public function setSpanId($span_id)
    {
        if (is_null($span_id)) {
            throw new \InvalidArgumentException('non-nullable span_id cannot be null');
        }
        $this->container['span_id'] = $span_id;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return \DateTime
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param \DateTime $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Beater\Client\Model\SpanStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Beater\Client\Model\SpanStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets tokens
     *
     * @return \Beater\Client\Model\TokenCounts|null
     */
    public function getTokens()
    {
        return $this->container['tokens'];
    }

    /**
     * Sets tokens
     *
     * @param \Beater\Client\Model\TokenCounts|null $tokens tokens
     *
     * @return self
     */
    public function setTokens($tokens)
    {
        if (is_null($tokens)) {
            array_push($this->openAPINullablesSetToNull, 'tokens');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tokens', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tokens'] = $tokens;

        return $this;
    }

    /**
     * Gets trace_id
     *
     * @return string
     */
    public function getTraceId()
    {
        return $this->container['trace_id'];
    }

    /**
     * Sets trace_id
     *
     * @param string $trace_id trace_id
     *
     * @return self
     */
    public function setTraceId($trace_id)
    {
        if (is_null($trace_id)) {
            throw new \InvalidArgumentException('non-nullable trace_id cannot be null');
        }
        $this->container['trace_id'] = $trace_id;

        return $this;
    }

    /**
     * Gets unmapped_attrs
     *
     * @return mixed
     */
    public function getUnmappedAttrs()
    {
        return $this->container['unmapped_attrs'];
    }

    /**
     * Sets unmapped_attrs
     *
     * @param mixed $unmapped_attrs unmapped_attrs
     *
     * @return self
     */
    public function setUnmappedAttrs($unmapped_attrs)
    {
        if (is_null($unmapped_attrs)) {
            array_push($this->openAPINullablesSetToNull, 'unmapped_attrs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unmapped_attrs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unmapped_attrs'] = $unmapped_attrs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
