<?php
/**
 * DatasetCase
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;

use \ArrayAccess;
use \Beater\Client\ObjectSerializer;

/**
 * DatasetCase Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DatasetCase implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DatasetCase';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'case_id' => 'string',
        'created_at' => '\DateTime',
        'dataset_id' => 'string',
        'input' => 'mixed',
        'input_artifact_hashes' => 'string[]',
        'normalizer_version' => 'string',
        'output' => 'mixed',
        'project_id' => 'string',
        'reference' => 'mixed',
        'source_environment_id' => 'string',
        'source_span_id' => 'string',
        'source_trace_id' => 'string',
        'tenant_id' => 'string',
        'trace' => 'mixed',
        'trace_schema_version' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'case_id' => null,
        'created_at' => 'date-time',
        'dataset_id' => null,
        'input' => null,
        'input_artifact_hashes' => null,
        'normalizer_version' => null,
        'output' => null,
        'project_id' => null,
        'reference' => null,
        'source_environment_id' => null,
        'source_span_id' => null,
        'source_trace_id' => null,
        'tenant_id' => null,
        'trace' => null,
        'trace_schema_version' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'case_id' => false,
        'created_at' => false,
        'dataset_id' => false,
        'input' => true,
        'input_artifact_hashes' => false,
        'normalizer_version' => false,
        'output' => true,
        'project_id' => false,
        'reference' => true,
        'source_environment_id' => false,
        'source_span_id' => false,
        'source_trace_id' => false,
        'tenant_id' => false,
        'trace' => true,
        'trace_schema_version' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'case_id' => 'case_id',
        'created_at' => 'created_at',
        'dataset_id' => 'dataset_id',
        'input' => 'input',
        'input_artifact_hashes' => 'input_artifact_hashes',
        'normalizer_version' => 'normalizer_version',
        'output' => 'output',
        'project_id' => 'project_id',
        'reference' => 'reference',
        'source_environment_id' => 'source_environment_id',
        'source_span_id' => 'source_span_id',
        'source_trace_id' => 'source_trace_id',
        'tenant_id' => 'tenant_id',
        'trace' => 'trace',
        'trace_schema_version' => 'trace_schema_version'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'case_id' => 'setCaseId',
        'created_at' => 'setCreatedAt',
        'dataset_id' => 'setDatasetId',
        'input' => 'setInput',
        'input_artifact_hashes' => 'setInputArtifactHashes',
        'normalizer_version' => 'setNormalizerVersion',
        'output' => 'setOutput',
        'project_id' => 'setProjectId',
        'reference' => 'setReference',
        'source_environment_id' => 'setSourceEnvironmentId',
        'source_span_id' => 'setSourceSpanId',
        'source_trace_id' => 'setSourceTraceId',
        'tenant_id' => 'setTenantId',
        'trace' => 'setTrace',
        'trace_schema_version' => 'setTraceSchemaVersion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'case_id' => 'getCaseId',
        'created_at' => 'getCreatedAt',
        'dataset_id' => 'getDatasetId',
        'input' => 'getInput',
        'input_artifact_hashes' => 'getInputArtifactHashes',
        'normalizer_version' => 'getNormalizerVersion',
        'output' => 'getOutput',
        'project_id' => 'getProjectId',
        'reference' => 'getReference',
        'source_environment_id' => 'getSourceEnvironmentId',
        'source_span_id' => 'getSourceSpanId',
        'source_trace_id' => 'getSourceTraceId',
        'tenant_id' => 'getTenantId',
        'trace' => 'getTrace',
        'trace_schema_version' => 'getTraceSchemaVersion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('case_id', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('dataset_id', $data ?? [], null);
        $this->setIfExists('input', $data ?? [], null);
        $this->setIfExists('input_artifact_hashes', $data ?? [], null);
        $this->setIfExists('normalizer_version', $data ?? [], null);
        $this->setIfExists('output', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('source_environment_id', $data ?? [], null);
        $this->setIfExists('source_span_id', $data ?? [], null);
        $this->setIfExists('source_trace_id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('trace', $data ?? [], null);
        $this->setIfExists('trace_schema_version', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['case_id'] === null) {
            $invalidProperties[] = "'case_id' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['dataset_id'] === null) {
            $invalidProperties[] = "'dataset_id' can't be null";
        }
        if ($this->container['input'] === null) {
            $invalidProperties[] = "'input' can't be null";
        }
        if ($this->container['input_artifact_hashes'] === null) {
            $invalidProperties[] = "'input_artifact_hashes' can't be null";
        }
        if ($this->container['normalizer_version'] === null) {
            $invalidProperties[] = "'normalizer_version' can't be null";
        }
        if ($this->container['output'] === null) {
            $invalidProperties[] = "'output' can't be null";
        }
        if ($this->container['project_id'] === null) {
            $invalidProperties[] = "'project_id' can't be null";
        }
        if ($this->container['source_environment_id'] === null) {
            $invalidProperties[] = "'source_environment_id' can't be null";
        }
        if ($this->container['source_span_id'] === null) {
            $invalidProperties[] = "'source_span_id' can't be null";
        }
        if ($this->container['source_trace_id'] === null) {
            $invalidProperties[] = "'source_trace_id' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if ($this->container['trace'] === null) {
            $invalidProperties[] = "'trace' can't be null";
        }
        if ($this->container['trace_schema_version'] === null) {
            $invalidProperties[] = "'trace_schema_version' can't be null";
        }
        if (($this->container['trace_schema_version'] < 0)) {
            $invalidProperties[] = "invalid value for 'trace_schema_version', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets case_id
     *
     * @return string
     */
    public function getCaseId()
    {
        return $this->container['case_id'];
    }

    /**
     * Sets case_id
     *
     * @param string $case_id case_id
     *
     * @return self
     */
    public function setCaseId($case_id)
    {
        if (is_null($case_id)) {
            throw new \InvalidArgumentException('non-nullable case_id cannot be null');
        }
        $this->container['case_id'] = $case_id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets dataset_id
     *
     * @return string
     */
    public function getDatasetId()
    {
        return $this->container['dataset_id'];
    }

    /**
     * Sets dataset_id
     *
     * @param string $dataset_id dataset_id
     *
     * @return self
     */
    public function setDatasetId($dataset_id)
    {
        if (is_null($dataset_id)) {
            throw new \InvalidArgumentException('non-nullable dataset_id cannot be null');
        }
        $this->container['dataset_id'] = $dataset_id;

        return $this;
    }

    /**
     * Gets input
     *
     * @return mixed
     */
    public function getInput()
    {
        return $this->container['input'];
    }

    /**
     * Sets input
     *
     * @param mixed $input input
     *
     * @return self
     */
    public function setInput($input)
    {
        if (is_null($input)) {
            array_push($this->openAPINullablesSetToNull, 'input');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('input', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['input'] = $input;

        return $this;
    }

    /**
     * Gets input_artifact_hashes
     *
     * @return string[]
     */
    public function getInputArtifactHashes()
    {
        return $this->container['input_artifact_hashes'];
    }

    /**
     * Sets input_artifact_hashes
     *
     * @param string[] $input_artifact_hashes input_artifact_hashes
     *
     * @return self
     */
    public function setInputArtifactHashes($input_artifact_hashes)
    {
        if (is_null($input_artifact_hashes)) {
            throw new \InvalidArgumentException('non-nullable input_artifact_hashes cannot be null');
        }
        $this->container['input_artifact_hashes'] = $input_artifact_hashes;

        return $this;
    }

    /**
     * Gets normalizer_version
     *
     * @return string
     */
    public function getNormalizerVersion()
    {
        return $this->container['normalizer_version'];
    }

    /**
     * Sets normalizer_version
     *
     * @param string $normalizer_version normalizer_version
     *
     * @return self
     */
    public function setNormalizerVersion($normalizer_version)
    {
        if (is_null($normalizer_version)) {
            throw new \InvalidArgumentException('non-nullable normalizer_version cannot be null');
        }
        $this->container['normalizer_version'] = $normalizer_version;

        return $this;
    }

    /**
     * Gets output
     *
     * @return mixed
     */
    public function getOutput()
    {
        return $this->container['output'];
    }

    /**
     * Sets output
     *
     * @param mixed $output output
     *
     * @return self
     */
    public function setOutput($output)
    {
        if (is_null($output)) {
            array_push($this->openAPINullablesSetToNull, 'output');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('output', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['output'] = $output;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return mixed|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param mixed|null $reference reference
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            array_push($this->openAPINullablesSetToNull, 'reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets source_environment_id
     *
     * @return string
     */
    public function getSourceEnvironmentId()
    {
        return $this->container['source_environment_id'];
    }

    /**
     * Sets source_environment_id
     *
     * @param string $source_environment_id source_environment_id
     *
     * @return self
     */
    public function setSourceEnvironmentId($source_environment_id)
    {
        if (is_null($source_environment_id)) {
            throw new \InvalidArgumentException('non-nullable source_environment_id cannot be null');
        }
        $this->container['source_environment_id'] = $source_environment_id;

        return $this;
    }

    /**
     * Gets source_span_id
     *
     * @return string
     */
    public function getSourceSpanId()
    {
        return $this->container['source_span_id'];
    }

    /**
     * Sets source_span_id
     *
     * @param string $source_span_id source_span_id
     *
     * @return self
     */
    public function setSourceSpanId($source_span_id)
    {
        if (is_null($source_span_id)) {
            throw new \InvalidArgumentException('non-nullable source_span_id cannot be null');
        }
        $this->container['source_span_id'] = $source_span_id;

        return $this;
    }

    /**
     * Gets source_trace_id
     *
     * @return string
     */
    public function getSourceTraceId()
    {
        return $this->container['source_trace_id'];
    }

    /**
     * Sets source_trace_id
     *
     * @param string $source_trace_id source_trace_id
     *
     * @return self
     */
    public function setSourceTraceId($source_trace_id)
    {
        if (is_null($source_trace_id)) {
            throw new \InvalidArgumentException('non-nullable source_trace_id cannot be null');
        }
        $this->container['source_trace_id'] = $source_trace_id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets trace
     *
     * @return mixed
     */
    public function getTrace()
    {
        return $this->container['trace'];
    }

    /**
     * Sets trace
     *
     * @param mixed $trace trace
     *
     * @return self
     */
    public function setTrace($trace)
    {
        if (is_null($trace)) {
            array_push($this->openAPINullablesSetToNull, 'trace');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('trace', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['trace'] = $trace;

        return $this;
    }

    /**
     * Gets trace_schema_version
     *
     * @return int
     */
    public function getTraceSchemaVersion()
    {
        return $this->container['trace_schema_version'];
    }

    /**
     * Sets trace_schema_version
     *
     * @param int $trace_schema_version trace_schema_version
     *
     * @return self
     */
    public function setTraceSchemaVersion($trace_schema_version)
    {
        if (is_null($trace_schema_version)) {
            throw new \InvalidArgumentException('non-nullable trace_schema_version cannot be null');
        }

        if (($trace_schema_version < 0)) {
            throw new \InvalidArgumentException('invalid value for $trace_schema_version when calling DatasetCase., must be bigger than or equal to 0.');
        }

        $this->container['trace_schema_version'] = $trace_schema_version;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
