<?php
/**
 * NativeIngestRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;

use \ArrayAccess;
use \Beater\Client\ObjectSerializer;

/**
 * NativeIngestRequest Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NativeIngestRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NativeIngestRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attributes' => 'array<string,mixed>',
        'auth_context' => '\Beater\Client\Model\AuthContext',
        'cost' => '\Beater\Client\Model\Money',
        'end_time' => '\DateTime',
        'idempotency_key' => 'string',
        'input' => 'mixed',
        'kind' => 'string',
        'model' => '\Beater\Client\Model\ModelRef',
        'name' => 'string',
        'output' => 'mixed',
        'parent_span_id' => 'string',
        'redaction_class' => '\Beater\Client\Model\RedactionClass',
        'scope' => '\Beater\Client\Model\TenantScope',
        'seq' => 'int',
        'span_id' => 'string',
        'start_time' => '\DateTime',
        'status' => '\Beater\Client\Model\SpanStatus',
        'tokens' => '\Beater\Client\Model\TokenCounts',
        'trace_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attributes' => null,
        'auth_context' => null,
        'cost' => null,
        'end_time' => 'date-time',
        'idempotency_key' => null,
        'input' => null,
        'kind' => null,
        'model' => null,
        'name' => null,
        'output' => null,
        'parent_span_id' => null,
        'redaction_class' => null,
        'scope' => null,
        'seq' => 'int64',
        'span_id' => null,
        'start_time' => 'date-time',
        'status' => null,
        'tokens' => null,
        'trace_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attributes' => false,
        'auth_context' => true,
        'cost' => true,
        'end_time' => true,
        'idempotency_key' => false,
        'input' => true,
        'kind' => false,
        'model' => true,
        'name' => false,
        'output' => true,
        'parent_span_id' => false,
        'redaction_class' => false,
        'scope' => false,
        'seq' => false,
        'span_id' => false,
        'start_time' => true,
        'status' => false,
        'tokens' => true,
        'trace_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attributes' => 'attributes',
        'auth_context' => 'auth_context',
        'cost' => 'cost',
        'end_time' => 'end_time',
        'idempotency_key' => 'idempotency_key',
        'input' => 'input',
        'kind' => 'kind',
        'model' => 'model',
        'name' => 'name',
        'output' => 'output',
        'parent_span_id' => 'parent_span_id',
        'redaction_class' => 'redaction_class',
        'scope' => 'scope',
        'seq' => 'seq',
        'span_id' => 'span_id',
        'start_time' => 'start_time',
        'status' => 'status',
        'tokens' => 'tokens',
        'trace_id' => 'trace_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attributes' => 'setAttributes',
        'auth_context' => 'setAuthContext',
        'cost' => 'setCost',
        'end_time' => 'setEndTime',
        'idempotency_key' => 'setIdempotencyKey',
        'input' => 'setInput',
        'kind' => 'setKind',
        'model' => 'setModel',
        'name' => 'setName',
        'output' => 'setOutput',
        'parent_span_id' => 'setParentSpanId',
        'redaction_class' => 'setRedactionClass',
        'scope' => 'setScope',
        'seq' => 'setSeq',
        'span_id' => 'setSpanId',
        'start_time' => 'setStartTime',
        'status' => 'setStatus',
        'tokens' => 'setTokens',
        'trace_id' => 'setTraceId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attributes' => 'getAttributes',
        'auth_context' => 'getAuthContext',
        'cost' => 'getCost',
        'end_time' => 'getEndTime',
        'idempotency_key' => 'getIdempotencyKey',
        'input' => 'getInput',
        'kind' => 'getKind',
        'model' => 'getModel',
        'name' => 'getName',
        'output' => 'getOutput',
        'parent_span_id' => 'getParentSpanId',
        'redaction_class' => 'getRedactionClass',
        'scope' => 'getScope',
        'seq' => 'getSeq',
        'span_id' => 'getSpanId',
        'start_time' => 'getStartTime',
        'status' => 'getStatus',
        'tokens' => 'getTokens',
        'trace_id' => 'getTraceId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('auth_context', $data ?? [], null);
        $this->setIfExists('cost', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('idempotency_key', $data ?? [], null);
        $this->setIfExists('input', $data ?? [], null);
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('output', $data ?? [], null);
        $this->setIfExists('parent_span_id', $data ?? [], null);
        $this->setIfExists('redaction_class', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('seq', $data ?? [], null);
        $this->setIfExists('span_id', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tokens', $data ?? [], null);
        $this->setIfExists('trace_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['attributes'] === null) {
            $invalidProperties[] = "'attributes' can't be null";
        }
        if ($this->container['kind'] === null) {
            $invalidProperties[] = "'kind' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['redaction_class'] === null) {
            $invalidProperties[] = "'redaction_class' can't be null";
        }
        if ($this->container['scope'] === null) {
            $invalidProperties[] = "'scope' can't be null";
        }
        if ($this->container['seq'] === null) {
            $invalidProperties[] = "'seq' can't be null";
        }
        if (($this->container['seq'] < 0)) {
            $invalidProperties[] = "invalid value for 'seq', must be bigger than or equal to 0.";
        }

        if ($this->container['span_id'] === null) {
            $invalidProperties[] = "'span_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['trace_id'] === null) {
            $invalidProperties[] = "'trace_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attributes
     *
     * @return array<string,mixed>
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param array<string,mixed> $attributes attributes
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets auth_context
     *
     * @return \Beater\Client\Model\AuthContext|null
     */
    public function getAuthContext()
    {
        return $this->container['auth_context'];
    }

    /**
     * Sets auth_context
     *
     * @param \Beater\Client\Model\AuthContext|null $auth_context auth_context
     *
     * @return self
     */
    public function setAuthContext($auth_context)
    {
        if (is_null($auth_context)) {
            array_push($this->openAPINullablesSetToNull, 'auth_context');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_context', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_context'] = $auth_context;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return \Beater\Client\Model\Money|null
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param \Beater\Client\Model\Money|null $cost cost
     *
     * @return self
     */
    public function setCost($cost)
    {
        if (is_null($cost)) {
            array_push($this->openAPINullablesSetToNull, 'cost');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cost', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return \DateTime|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param \DateTime|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            array_push($this->openAPINullablesSetToNull, 'end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets idempotency_key
     *
     * @return string|null
     */
    public function getIdempotencyKey()
    {
        return $this->container['idempotency_key'];
    }

    /**
     * Sets idempotency_key
     *
     * @param string|null $idempotency_key idempotency_key
     *
     * @return self
     */
    public function setIdempotencyKey($idempotency_key)
    {
        if (is_null($idempotency_key)) {
            throw new \InvalidArgumentException('non-nullable idempotency_key cannot be null');
        }
        $this->container['idempotency_key'] = $idempotency_key;

        return $this;
    }

    /**
     * Gets input
     *
     * @return mixed|null
     */
    public function getInput()
    {
        return $this->container['input'];
    }

    /**
     * Sets input
     *
     * @param mixed|null $input input
     *
     * @return self
     */
    public function setInput($input)
    {
        if (is_null($input)) {
            array_push($this->openAPINullablesSetToNull, 'input');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('input', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['input'] = $input;

        return $this;
    }

    /**
     * Gets kind
     *
     * @return string
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string $kind Canonical agent span kind such as agent.run or llm.call
     *
     * @return self
     */
    public function setKind($kind)
    {
        if (is_null($kind)) {
            throw new \InvalidArgumentException('non-nullable kind cannot be null');
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets model
     *
     * @return \Beater\Client\Model\ModelRef|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param \Beater\Client\Model\ModelRef|null $model model
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            array_push($this->openAPINullablesSetToNull, 'model');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('model', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets output
     *
     * @return mixed|null
     */
    public function getOutput()
    {
        return $this->container['output'];
    }

    /**
     * Sets output
     *
     * @param mixed|null $output output
     *
     * @return self
     */
    public function setOutput($output)
    {
        if (is_null($output)) {
            array_push($this->openAPINullablesSetToNull, 'output');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('output', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['output'] = $output;

        return $this;
    }

    /**
     * Gets parent_span_id
     *
     * @return string|null
     */
    public function getParentSpanId()
    {
        return $this->container['parent_span_id'];
    }

    /**
     * Sets parent_span_id
     *
     * @param string|null $parent_span_id parent_span_id
     *
     * @return self
     */
    public function setParentSpanId($parent_span_id)
    {
        if (is_null($parent_span_id)) {
            throw new \InvalidArgumentException('non-nullable parent_span_id cannot be null');
        }
        $this->container['parent_span_id'] = $parent_span_id;

        return $this;
    }

    /**
     * Gets redaction_class
     *
     * @return \Beater\Client\Model\RedactionClass
     */
    public function getRedactionClass()
    {
        return $this->container['redaction_class'];
    }

    /**
     * Sets redaction_class
     *
     * @param \Beater\Client\Model\RedactionClass $redaction_class redaction_class
     *
     * @return self
     */
    public function setRedactionClass($redaction_class)
    {
        if (is_null($redaction_class)) {
            throw new \InvalidArgumentException('non-nullable redaction_class cannot be null');
        }
        $this->container['redaction_class'] = $redaction_class;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return \Beater\Client\Model\TenantScope
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param \Beater\Client\Model\TenantScope $scope scope
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets seq
     *
     * @return int
     */
    public function getSeq()
    {
        return $this->container['seq'];
    }

    /**
     * Sets seq
     *
     * @param int $seq seq
     *
     * @return self
     */
    public function setSeq($seq)
    {
        if (is_null($seq)) {
            throw new \InvalidArgumentException('non-nullable seq cannot be null');
        }

        if (($seq < 0)) {
            throw new \InvalidArgumentException('invalid value for $seq when calling NativeIngestRequest., must be bigger than or equal to 0.');
        }

        $this->container['seq'] = $seq;

        return $this;
    }

    /**
     * Gets span_id
     *
     * @return string
     */
    public function getSpanId()
    {
        return $this->container['span_id'];
    }

    /**
     * Sets span_id
     *
     * @param string $span_id span_id
     *
     * @return self
     */
    public function setSpanId($span_id)
    {
        if (is_null($span_id)) {
            throw new \InvalidArgumentException('non-nullable span_id cannot be null');
        }
        $this->container['span_id'] = $span_id;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return \DateTime|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param \DateTime|null $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            array_push($this->openAPINullablesSetToNull, 'start_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Beater\Client\Model\SpanStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Beater\Client\Model\SpanStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tokens
     *
     * @return \Beater\Client\Model\TokenCounts|null
     */
    public function getTokens()
    {
        return $this->container['tokens'];
    }

    /**
     * Sets tokens
     *
     * @param \Beater\Client\Model\TokenCounts|null $tokens tokens
     *
     * @return self
     */
    public function setTokens($tokens)
    {
        if (is_null($tokens)) {
            array_push($this->openAPINullablesSetToNull, 'tokens');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tokens', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tokens'] = $tokens;

        return $this;
    }

    /**
     * Gets trace_id
     *
     * @return string
     */
    public function getTraceId()
    {
        return $this->container['trace_id'];
    }

    /**
     * Sets trace_id
     *
     * @param string $trace_id trace_id
     *
     * @return self
     */
    public function setTraceId($trace_id)
    {
        if (is_null($trace_id)) {
            throw new \InvalidArgumentException('non-nullable trace_id cannot be null');
        }
        $this->container['trace_id'] = $trace_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
