<?php
/**
 * StatisticalTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;
use \Beater\Client\ObjectSerializer;

/**
 * StatisticalTest Class Doc Comment
 *
 * @category Class
 * @description The statistical test that produced an [&#x60;ExperimentComparison&#x60;]. The gate records which method was **actually executed** so a reader can tell a t-test result from an exact McNemar, Wilcoxon, bootstrap, cluster-robust, or anytime-valid sequential one. The old single &#x60;PairedNormalApproximation&#x60; (a hard-coded-z normal approximation with no p-value) is gone — see &#x60;beater-stats&#x60;.
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatisticalTest
{
    /**
     * Possible values of this enum
     */
    public const PAIRED_T = 'paired_t';

    public const MCNEMAR_EXACT = 'mcnemar_exact';

    public const WILCOXON_SIGNED_RANK = 'wilcoxon_signed_rank';

    public const PAIRED_BOOTSTRAP = 'paired_bootstrap';

    public const CLUSTERED_PAIRED_T = 'clustered_paired_t';

    public const SEQUENTIAL_E_VALUE = 'sequential_e_value';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAIRED_T,
            self::MCNEMAR_EXACT,
            self::WILCOXON_SIGNED_RANK,
            self::PAIRED_BOOTSTRAP,
            self::CLUSTERED_PAIRED_T,
            self::SEQUENTIAL_E_VALUE
        ];
    }
}
