<?php
/**
 * TraceWriteDrainReport
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Model;

use \ArrayAccess;
use \Beater\Client\ObjectSerializer;

/**
 * TraceWriteDrainReport Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TraceWriteDrainReport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TraceWriteDrainReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'consumed' => 'int',
        'dead_lettered' => 'int',
        'downstream_published' => 'int',
        'duplicate_raw' => 'int',
        'duplicate_spans' => 'int',
        'failed_downstream_publishes' => 'int',
        'failed_writes' => 'int',
        'invalid_messages' => 'int',
        'retried' => 'int',
        'trace_ids' => 'string[]',
        'trace_refs' => '\Beater\Client\Model\QueuedTraceWork[]',
        'written_raw' => 'int',
        'written_spans' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'consumed' => null,
        'dead_lettered' => null,
        'downstream_published' => null,
        'duplicate_raw' => null,
        'duplicate_spans' => null,
        'failed_downstream_publishes' => null,
        'failed_writes' => null,
        'invalid_messages' => null,
        'retried' => null,
        'trace_ids' => null,
        'trace_refs' => null,
        'written_raw' => null,
        'written_spans' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'consumed' => false,
        'dead_lettered' => false,
        'downstream_published' => false,
        'duplicate_raw' => false,
        'duplicate_spans' => false,
        'failed_downstream_publishes' => false,
        'failed_writes' => false,
        'invalid_messages' => false,
        'retried' => false,
        'trace_ids' => false,
        'trace_refs' => false,
        'written_raw' => false,
        'written_spans' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'consumed' => 'consumed',
        'dead_lettered' => 'dead_lettered',
        'downstream_published' => 'downstream_published',
        'duplicate_raw' => 'duplicate_raw',
        'duplicate_spans' => 'duplicate_spans',
        'failed_downstream_publishes' => 'failed_downstream_publishes',
        'failed_writes' => 'failed_writes',
        'invalid_messages' => 'invalid_messages',
        'retried' => 'retried',
        'trace_ids' => 'trace_ids',
        'trace_refs' => 'trace_refs',
        'written_raw' => 'written_raw',
        'written_spans' => 'written_spans'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'consumed' => 'setConsumed',
        'dead_lettered' => 'setDeadLettered',
        'downstream_published' => 'setDownstreamPublished',
        'duplicate_raw' => 'setDuplicateRaw',
        'duplicate_spans' => 'setDuplicateSpans',
        'failed_downstream_publishes' => 'setFailedDownstreamPublishes',
        'failed_writes' => 'setFailedWrites',
        'invalid_messages' => 'setInvalidMessages',
        'retried' => 'setRetried',
        'trace_ids' => 'setTraceIds',
        'trace_refs' => 'setTraceRefs',
        'written_raw' => 'setWrittenRaw',
        'written_spans' => 'setWrittenSpans'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'consumed' => 'getConsumed',
        'dead_lettered' => 'getDeadLettered',
        'downstream_published' => 'getDownstreamPublished',
        'duplicate_raw' => 'getDuplicateRaw',
        'duplicate_spans' => 'getDuplicateSpans',
        'failed_downstream_publishes' => 'getFailedDownstreamPublishes',
        'failed_writes' => 'getFailedWrites',
        'invalid_messages' => 'getInvalidMessages',
        'retried' => 'getRetried',
        'trace_ids' => 'getTraceIds',
        'trace_refs' => 'getTraceRefs',
        'written_raw' => 'getWrittenRaw',
        'written_spans' => 'getWrittenSpans'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('consumed', $data ?? [], null);
        $this->setIfExists('dead_lettered', $data ?? [], null);
        $this->setIfExists('downstream_published', $data ?? [], null);
        $this->setIfExists('duplicate_raw', $data ?? [], null);
        $this->setIfExists('duplicate_spans', $data ?? [], null);
        $this->setIfExists('failed_downstream_publishes', $data ?? [], null);
        $this->setIfExists('failed_writes', $data ?? [], null);
        $this->setIfExists('invalid_messages', $data ?? [], null);
        $this->setIfExists('retried', $data ?? [], null);
        $this->setIfExists('trace_ids', $data ?? [], null);
        $this->setIfExists('trace_refs', $data ?? [], null);
        $this->setIfExists('written_raw', $data ?? [], null);
        $this->setIfExists('written_spans', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['consumed'] === null) {
            $invalidProperties[] = "'consumed' can't be null";
        }
        if (($this->container['consumed'] < 0)) {
            $invalidProperties[] = "invalid value for 'consumed', must be bigger than or equal to 0.";
        }

        if ($this->container['dead_lettered'] === null) {
            $invalidProperties[] = "'dead_lettered' can't be null";
        }
        if (($this->container['dead_lettered'] < 0)) {
            $invalidProperties[] = "invalid value for 'dead_lettered', must be bigger than or equal to 0.";
        }

        if ($this->container['downstream_published'] === null) {
            $invalidProperties[] = "'downstream_published' can't be null";
        }
        if (($this->container['downstream_published'] < 0)) {
            $invalidProperties[] = "invalid value for 'downstream_published', must be bigger than or equal to 0.";
        }

        if ($this->container['duplicate_raw'] === null) {
            $invalidProperties[] = "'duplicate_raw' can't be null";
        }
        if (($this->container['duplicate_raw'] < 0)) {
            $invalidProperties[] = "invalid value for 'duplicate_raw', must be bigger than or equal to 0.";
        }

        if ($this->container['duplicate_spans'] === null) {
            $invalidProperties[] = "'duplicate_spans' can't be null";
        }
        if (($this->container['duplicate_spans'] < 0)) {
            $invalidProperties[] = "invalid value for 'duplicate_spans', must be bigger than or equal to 0.";
        }

        if ($this->container['failed_downstream_publishes'] === null) {
            $invalidProperties[] = "'failed_downstream_publishes' can't be null";
        }
        if (($this->container['failed_downstream_publishes'] < 0)) {
            $invalidProperties[] = "invalid value for 'failed_downstream_publishes', must be bigger than or equal to 0.";
        }

        if ($this->container['failed_writes'] === null) {
            $invalidProperties[] = "'failed_writes' can't be null";
        }
        if (($this->container['failed_writes'] < 0)) {
            $invalidProperties[] = "invalid value for 'failed_writes', must be bigger than or equal to 0.";
        }

        if ($this->container['invalid_messages'] === null) {
            $invalidProperties[] = "'invalid_messages' can't be null";
        }
        if (($this->container['invalid_messages'] < 0)) {
            $invalidProperties[] = "invalid value for 'invalid_messages', must be bigger than or equal to 0.";
        }

        if ($this->container['retried'] === null) {
            $invalidProperties[] = "'retried' can't be null";
        }
        if (($this->container['retried'] < 0)) {
            $invalidProperties[] = "invalid value for 'retried', must be bigger than or equal to 0.";
        }

        if ($this->container['trace_ids'] === null) {
            $invalidProperties[] = "'trace_ids' can't be null";
        }
        if ($this->container['trace_refs'] === null) {
            $invalidProperties[] = "'trace_refs' can't be null";
        }
        if ($this->container['written_raw'] === null) {
            $invalidProperties[] = "'written_raw' can't be null";
        }
        if (($this->container['written_raw'] < 0)) {
            $invalidProperties[] = "invalid value for 'written_raw', must be bigger than or equal to 0.";
        }

        if ($this->container['written_spans'] === null) {
            $invalidProperties[] = "'written_spans' can't be null";
        }
        if (($this->container['written_spans'] < 0)) {
            $invalidProperties[] = "invalid value for 'written_spans', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets consumed
     *
     * @return int
     */
    public function getConsumed()
    {
        return $this->container['consumed'];
    }

    /**
     * Sets consumed
     *
     * @param int $consumed consumed
     *
     * @return self
     */
    public function setConsumed($consumed)
    {
        if (is_null($consumed)) {
            throw new \InvalidArgumentException('non-nullable consumed cannot be null');
        }

        if (($consumed < 0)) {
            throw new \InvalidArgumentException('invalid value for $consumed when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['consumed'] = $consumed;

        return $this;
    }

    /**
     * Gets dead_lettered
     *
     * @return int
     */
    public function getDeadLettered()
    {
        return $this->container['dead_lettered'];
    }

    /**
     * Sets dead_lettered
     *
     * @param int $dead_lettered dead_lettered
     *
     * @return self
     */
    public function setDeadLettered($dead_lettered)
    {
        if (is_null($dead_lettered)) {
            throw new \InvalidArgumentException('non-nullable dead_lettered cannot be null');
        }

        if (($dead_lettered < 0)) {
            throw new \InvalidArgumentException('invalid value for $dead_lettered when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['dead_lettered'] = $dead_lettered;

        return $this;
    }

    /**
     * Gets downstream_published
     *
     * @return int
     */
    public function getDownstreamPublished()
    {
        return $this->container['downstream_published'];
    }

    /**
     * Sets downstream_published
     *
     * @param int $downstream_published downstream_published
     *
     * @return self
     */
    public function setDownstreamPublished($downstream_published)
    {
        if (is_null($downstream_published)) {
            throw new \InvalidArgumentException('non-nullable downstream_published cannot be null');
        }

        if (($downstream_published < 0)) {
            throw new \InvalidArgumentException('invalid value for $downstream_published when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['downstream_published'] = $downstream_published;

        return $this;
    }

    /**
     * Gets duplicate_raw
     *
     * @return int
     */
    public function getDuplicateRaw()
    {
        return $this->container['duplicate_raw'];
    }

    /**
     * Sets duplicate_raw
     *
     * @param int $duplicate_raw duplicate_raw
     *
     * @return self
     */
    public function setDuplicateRaw($duplicate_raw)
    {
        if (is_null($duplicate_raw)) {
            throw new \InvalidArgumentException('non-nullable duplicate_raw cannot be null');
        }

        if (($duplicate_raw < 0)) {
            throw new \InvalidArgumentException('invalid value for $duplicate_raw when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['duplicate_raw'] = $duplicate_raw;

        return $this;
    }

    /**
     * Gets duplicate_spans
     *
     * @return int
     */
    public function getDuplicateSpans()
    {
        return $this->container['duplicate_spans'];
    }

    /**
     * Sets duplicate_spans
     *
     * @param int $duplicate_spans duplicate_spans
     *
     * @return self
     */
    public function setDuplicateSpans($duplicate_spans)
    {
        if (is_null($duplicate_spans)) {
            throw new \InvalidArgumentException('non-nullable duplicate_spans cannot be null');
        }

        if (($duplicate_spans < 0)) {
            throw new \InvalidArgumentException('invalid value for $duplicate_spans when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['duplicate_spans'] = $duplicate_spans;

        return $this;
    }

    /**
     * Gets failed_downstream_publishes
     *
     * @return int
     */
    public function getFailedDownstreamPublishes()
    {
        return $this->container['failed_downstream_publishes'];
    }

    /**
     * Sets failed_downstream_publishes
     *
     * @param int $failed_downstream_publishes failed_downstream_publishes
     *
     * @return self
     */
    public function setFailedDownstreamPublishes($failed_downstream_publishes)
    {
        if (is_null($failed_downstream_publishes)) {
            throw new \InvalidArgumentException('non-nullable failed_downstream_publishes cannot be null');
        }

        if (($failed_downstream_publishes < 0)) {
            throw new \InvalidArgumentException('invalid value for $failed_downstream_publishes when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['failed_downstream_publishes'] = $failed_downstream_publishes;

        return $this;
    }

    /**
     * Gets failed_writes
     *
     * @return int
     */
    public function getFailedWrites()
    {
        return $this->container['failed_writes'];
    }

    /**
     * Sets failed_writes
     *
     * @param int $failed_writes failed_writes
     *
     * @return self
     */
    public function setFailedWrites($failed_writes)
    {
        if (is_null($failed_writes)) {
            throw new \InvalidArgumentException('non-nullable failed_writes cannot be null');
        }

        if (($failed_writes < 0)) {
            throw new \InvalidArgumentException('invalid value for $failed_writes when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['failed_writes'] = $failed_writes;

        return $this;
    }

    /**
     * Gets invalid_messages
     *
     * @return int
     */
    public function getInvalidMessages()
    {
        return $this->container['invalid_messages'];
    }

    /**
     * Sets invalid_messages
     *
     * @param int $invalid_messages invalid_messages
     *
     * @return self
     */
    public function setInvalidMessages($invalid_messages)
    {
        if (is_null($invalid_messages)) {
            throw new \InvalidArgumentException('non-nullable invalid_messages cannot be null');
        }

        if (($invalid_messages < 0)) {
            throw new \InvalidArgumentException('invalid value for $invalid_messages when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['invalid_messages'] = $invalid_messages;

        return $this;
    }

    /**
     * Gets retried
     *
     * @return int
     */
    public function getRetried()
    {
        return $this->container['retried'];
    }

    /**
     * Sets retried
     *
     * @param int $retried retried
     *
     * @return self
     */
    public function setRetried($retried)
    {
        if (is_null($retried)) {
            throw new \InvalidArgumentException('non-nullable retried cannot be null');
        }

        if (($retried < 0)) {
            throw new \InvalidArgumentException('invalid value for $retried when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['retried'] = $retried;

        return $this;
    }

    /**
     * Gets trace_ids
     *
     * @return string[]
     */
    public function getTraceIds()
    {
        return $this->container['trace_ids'];
    }

    /**
     * Sets trace_ids
     *
     * @param string[] $trace_ids trace_ids
     *
     * @return self
     */
    public function setTraceIds($trace_ids)
    {
        if (is_null($trace_ids)) {
            throw new \InvalidArgumentException('non-nullable trace_ids cannot be null');
        }
        $this->container['trace_ids'] = $trace_ids;

        return $this;
    }

    /**
     * Gets trace_refs
     *
     * @return \Beater\Client\Model\QueuedTraceWork[]
     */
    public function getTraceRefs()
    {
        return $this->container['trace_refs'];
    }

    /**
     * Sets trace_refs
     *
     * @param \Beater\Client\Model\QueuedTraceWork[] $trace_refs trace_refs
     *
     * @return self
     */
    public function setTraceRefs($trace_refs)
    {
        if (is_null($trace_refs)) {
            throw new \InvalidArgumentException('non-nullable trace_refs cannot be null');
        }
        $this->container['trace_refs'] = $trace_refs;

        return $this;
    }

    /**
     * Gets written_raw
     *
     * @return int
     */
    public function getWrittenRaw()
    {
        return $this->container['written_raw'];
    }

    /**
     * Sets written_raw
     *
     * @param int $written_raw written_raw
     *
     * @return self
     */
    public function setWrittenRaw($written_raw)
    {
        if (is_null($written_raw)) {
            throw new \InvalidArgumentException('non-nullable written_raw cannot be null');
        }

        if (($written_raw < 0)) {
            throw new \InvalidArgumentException('invalid value for $written_raw when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['written_raw'] = $written_raw;

        return $this;
    }

    /**
     * Gets written_spans
     *
     * @return int
     */
    public function getWrittenSpans()
    {
        return $this->container['written_spans'];
    }

    /**
     * Sets written_spans
     *
     * @param int $written_spans written_spans
     *
     * @return self
     */
    public function setWrittenSpans($written_spans)
    {
        if (is_null($written_spans)) {
            throw new \InvalidArgumentException('non-nullable written_spans cannot be null');
        }

        if (($written_spans < 0)) {
            throw new \InvalidArgumentException('invalid value for $written_spans when calling TraceWriteDrainReport., must be bigger than or equal to 0.');
        }

        $this->container['written_spans'] = $written_spans;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
