/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Token usage in the OpenAI-compatible response shape.
 * @export
 * @interface ChatCompletionUsage
 */
export interface ChatCompletionUsage {
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionUsage
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionUsage
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionUsage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the ChatCompletionUsage interface.
 */
export function instanceOfChatCompletionUsage(value: object): value is ChatCompletionUsage {
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function ChatCompletionUsageFromJSON(json: any): ChatCompletionUsage {
    return ChatCompletionUsageFromJSONTyped(json, false);
}

export function ChatCompletionUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'completionTokens': json['completion_tokens'],
        'promptTokens': json['prompt_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function ChatCompletionUsageToJSON(json: any): ChatCompletionUsage {
    return ChatCompletionUsageToJSONTyped(json, false);
}

export function ChatCompletionUsageToJSONTyped(value?: ChatCompletionUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completion_tokens': value['completionTokens'],
        'prompt_tokens': value['promptTokens'],
        'total_tokens': value['totalTokens'],
    };
}

