/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * One choice in an OpenAI-compatible response.
 * @export
 * @interface ChatCompletionChoice
 */
export interface ChatCompletionChoice {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionChoice
     */
    finishReason?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionChoice
     */
    index: number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatCompletionChoice
     */
    message: ChatMessage;
}

/**
 * Check if a given object implements the ChatCompletionChoice interface.
 */
export function instanceOfChatCompletionChoice(value: object): value is ChatCompletionChoice {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ChatCompletionChoiceFromJSON(json: any): ChatCompletionChoice {
    return ChatCompletionChoiceFromJSONTyped(json, false);
}

export function ChatCompletionChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
        'index': json['index'],
        'message': ChatMessageFromJSON(json['message']),
    };
}

export function ChatCompletionChoiceToJSON(json: any): ChatCompletionChoice {
    return ChatCompletionChoiceToJSONTyped(json, false);
}

export function ChatCompletionChoiceToJSONTyped(value?: ChatCompletionChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'finish_reason': value['finishReason'],
        'index': value['index'],
        'message': ChatMessageToJSON(value['message']),
    };
}

