/*
Beater API

Testing GatewayAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package beaterclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/beaterclient"
)

func Test_beaterclient_GatewayAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GatewayAPIService GatewayChatCompletions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var projectId string
		var environmentId string

		resp, httpRes, err := apiClient.GatewayAPI.GatewayChatCompletions(context.Background(), tenantId, projectId, environmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
