/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GatewayOutcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayOutcome{}

// GatewayOutcome The result of a successfully proxied completion.
type GatewayOutcome struct {
	Attempts int32 `json:"attempts"`
	Cached bool `json:"cached"`
	Cost Money `json:"cost"`
	Model ModelRef `json:"model"`
	Provider string `json:"provider"`
	RequestHash string `json:"request_hash"`
	Response ChatCompletionResponse `json:"response"`
	Tokens TokenCounts `json:"tokens"`
}

type _GatewayOutcome GatewayOutcome

// NewGatewayOutcome instantiates a new GatewayOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayOutcome(attempts int32, cached bool, cost Money, model ModelRef, provider string, requestHash string, response ChatCompletionResponse, tokens TokenCounts) *GatewayOutcome {
	this := GatewayOutcome{}
	this.Attempts = attempts
	this.Cached = cached
	this.Cost = cost
	this.Model = model
	this.Provider = provider
	this.RequestHash = requestHash
	this.Response = response
	this.Tokens = tokens
	return &this
}

// NewGatewayOutcomeWithDefaults instantiates a new GatewayOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayOutcomeWithDefaults() *GatewayOutcome {
	this := GatewayOutcome{}
	return &this
}

// GetAttempts returns the Attempts field value
func (o *GatewayOutcome) GetAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempts, true
}

// SetAttempts sets field value
func (o *GatewayOutcome) SetAttempts(v int32) {
	o.Attempts = v
}

// GetCached returns the Cached field value
func (o *GatewayOutcome) GetCached() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cached
}

// GetCachedOk returns a tuple with the Cached field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetCachedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cached, true
}

// SetCached sets field value
func (o *GatewayOutcome) SetCached(v bool) {
	o.Cached = v
}

// GetCost returns the Cost field value
func (o *GatewayOutcome) GetCost() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.Cost
}

// GetCostOk returns a tuple with the Cost field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetCostOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cost, true
}

// SetCost sets field value
func (o *GatewayOutcome) SetCost(v Money) {
	o.Cost = v
}

// GetModel returns the Model field value
func (o *GatewayOutcome) GetModel() ModelRef {
	if o == nil {
		var ret ModelRef
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetModelOk() (*ModelRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *GatewayOutcome) SetModel(v ModelRef) {
	o.Model = v
}

// GetProvider returns the Provider field value
func (o *GatewayOutcome) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *GatewayOutcome) SetProvider(v string) {
	o.Provider = v
}

// GetRequestHash returns the RequestHash field value
func (o *GatewayOutcome) GetRequestHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestHash
}

// GetRequestHashOk returns a tuple with the RequestHash field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetRequestHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestHash, true
}

// SetRequestHash sets field value
func (o *GatewayOutcome) SetRequestHash(v string) {
	o.RequestHash = v
}

// GetResponse returns the Response field value
func (o *GatewayOutcome) GetResponse() ChatCompletionResponse {
	if o == nil {
		var ret ChatCompletionResponse
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetResponseOk() (*ChatCompletionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *GatewayOutcome) SetResponse(v ChatCompletionResponse) {
	o.Response = v
}

// GetTokens returns the Tokens field value
func (o *GatewayOutcome) GetTokens() TokenCounts {
	if o == nil {
		var ret TokenCounts
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *GatewayOutcome) GetTokensOk() (*TokenCounts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tokens, true
}

// SetTokens sets field value
func (o *GatewayOutcome) SetTokens(v TokenCounts) {
	o.Tokens = v
}

func (o GatewayOutcome) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayOutcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempts"] = o.Attempts
	toSerialize["cached"] = o.Cached
	toSerialize["cost"] = o.Cost
	toSerialize["model"] = o.Model
	toSerialize["provider"] = o.Provider
	toSerialize["request_hash"] = o.RequestHash
	toSerialize["response"] = o.Response
	toSerialize["tokens"] = o.Tokens
	return toSerialize, nil
}

func (o *GatewayOutcome) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempts",
		"cached",
		"cost",
		"model",
		"provider",
		"request_hash",
		"response",
		"tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayOutcome := _GatewayOutcome{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayOutcome)

	if err != nil {
		return err
	}

	*o = GatewayOutcome(varGatewayOutcome)

	return err
}

type NullableGatewayOutcome struct {
	value *GatewayOutcome
	isSet bool
}

func (v NullableGatewayOutcome) Get() *GatewayOutcome {
	return v.value
}

func (v *NullableGatewayOutcome) Set(val *GatewayOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayOutcome(val *GatewayOutcome) *NullableGatewayOutcome {
	return &NullableGatewayOutcome{value: val, isSet: true}
}

func (v NullableGatewayOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


