/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatCompletionUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionUsage{}

// ChatCompletionUsage Token usage in the OpenAI-compatible response shape.
type ChatCompletionUsage struct {
	CompletionTokens int64 `json:"completion_tokens"`
	PromptTokens int64 `json:"prompt_tokens"`
	TotalTokens int64 `json:"total_tokens"`
}

type _ChatCompletionUsage ChatCompletionUsage

// NewChatCompletionUsage instantiates a new ChatCompletionUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionUsage(completionTokens int64, promptTokens int64, totalTokens int64) *ChatCompletionUsage {
	this := ChatCompletionUsage{}
	this.CompletionTokens = completionTokens
	this.PromptTokens = promptTokens
	this.TotalTokens = totalTokens
	return &this
}

// NewChatCompletionUsageWithDefaults instantiates a new ChatCompletionUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionUsageWithDefaults() *ChatCompletionUsage {
	this := ChatCompletionUsage{}
	return &this
}

// GetCompletionTokens returns the CompletionTokens field value
func (o *ChatCompletionUsage) GetCompletionTokens() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CompletionTokens
}

// GetCompletionTokensOk returns a tuple with the CompletionTokens field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionUsage) GetCompletionTokensOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletionTokens, true
}

// SetCompletionTokens sets field value
func (o *ChatCompletionUsage) SetCompletionTokens(v int64) {
	o.CompletionTokens = v
}

// GetPromptTokens returns the PromptTokens field value
func (o *ChatCompletionUsage) GetPromptTokens() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PromptTokens
}

// GetPromptTokensOk returns a tuple with the PromptTokens field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionUsage) GetPromptTokensOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptTokens, true
}

// SetPromptTokens sets field value
func (o *ChatCompletionUsage) SetPromptTokens(v int64) {
	o.PromptTokens = v
}

// GetTotalTokens returns the TotalTokens field value
func (o *ChatCompletionUsage) GetTotalTokens() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionUsage) GetTotalTokensOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalTokens, true
}

// SetTotalTokens sets field value
func (o *ChatCompletionUsage) SetTotalTokens(v int64) {
	o.TotalTokens = v
}

func (o ChatCompletionUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["completion_tokens"] = o.CompletionTokens
	toSerialize["prompt_tokens"] = o.PromptTokens
	toSerialize["total_tokens"] = o.TotalTokens
	return toSerialize, nil
}

func (o *ChatCompletionUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"completion_tokens",
		"prompt_tokens",
		"total_tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatCompletionUsage := _ChatCompletionUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatCompletionUsage)

	if err != nil {
		return err
	}

	*o = ChatCompletionUsage(varChatCompletionUsage)

	return err
}

type NullableChatCompletionUsage struct {
	value *ChatCompletionUsage
	isSet bool
}

func (v NullableChatCompletionUsage) Get() *ChatCompletionUsage {
	return v.value
}

func (v *NullableChatCompletionUsage) Set(val *ChatCompletionUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionUsage(val *ChatCompletionUsage) *NullableChatCompletionUsage {
	return &NullableChatCompletionUsage{value: val, isSet: true}
}

func (v NullableChatCompletionUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


