/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelRoutingOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelRoutingOneOf1{}

// ModelRoutingOneOf1 Use the managed default model (hosted only).
type ModelRoutingOneOf1 struct {
	DefaultModel ModelRef `json:"default_model"`
	Kind string `json:"kind"`
}

type _ModelRoutingOneOf1 ModelRoutingOneOf1

// NewModelRoutingOneOf1 instantiates a new ModelRoutingOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelRoutingOneOf1(defaultModel ModelRef, kind string) *ModelRoutingOneOf1 {
	this := ModelRoutingOneOf1{}
	this.DefaultModel = defaultModel
	this.Kind = kind
	return &this
}

// NewModelRoutingOneOf1WithDefaults instantiates a new ModelRoutingOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelRoutingOneOf1WithDefaults() *ModelRoutingOneOf1 {
	this := ModelRoutingOneOf1{}
	return &this
}

// GetDefaultModel returns the DefaultModel field value
func (o *ModelRoutingOneOf1) GetDefaultModel() ModelRef {
	if o == nil {
		var ret ModelRef
		return ret
	}

	return o.DefaultModel
}

// GetDefaultModelOk returns a tuple with the DefaultModel field value
// and a boolean to check if the value has been set.
func (o *ModelRoutingOneOf1) GetDefaultModelOk() (*ModelRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultModel, true
}

// SetDefaultModel sets field value
func (o *ModelRoutingOneOf1) SetDefaultModel(v ModelRef) {
	o.DefaultModel = v
}

// GetKind returns the Kind field value
func (o *ModelRoutingOneOf1) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ModelRoutingOneOf1) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ModelRoutingOneOf1) SetKind(v string) {
	o.Kind = v
}

func (o ModelRoutingOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelRoutingOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default_model"] = o.DefaultModel
	toSerialize["kind"] = o.Kind
	return toSerialize, nil
}

func (o *ModelRoutingOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default_model",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelRoutingOneOf1 := _ModelRoutingOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelRoutingOneOf1)

	if err != nil {
		return err
	}

	*o = ModelRoutingOneOf1(varModelRoutingOneOf1)

	return err
}

type NullableModelRoutingOneOf1 struct {
	value *ModelRoutingOneOf1
	isSet bool
}

func (v NullableModelRoutingOneOf1) Get() *ModelRoutingOneOf1 {
	return v.value
}

func (v *NullableModelRoutingOneOf1) Set(val *ModelRoutingOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableModelRoutingOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableModelRoutingOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelRoutingOneOf1(val *ModelRoutingOneOf1) *NullableModelRoutingOneOf1 {
	return &NullableModelRoutingOneOf1{value: val, isSet: true}
}

func (v NullableModelRoutingOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelRoutingOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


