# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from beater_client.models.chat_completion_response import ChatCompletionResponse
from beater_client.models.model_ref import ModelRef
from beater_client.models.money import Money
from beater_client.models.token_counts import TokenCounts
from typing import Optional, Set
from typing_extensions import Self

class GatewayOutcome(BaseModel):
    """
    The result of a successfully proxied completion.
    """ # noqa: E501
    attempts: Annotated[int, Field(strict=True, ge=0)]
    cached: StrictBool
    cost: Money
    model: ModelRef
    provider: StrictStr
    request_hash: StrictStr
    response: ChatCompletionResponse
    tokens: TokenCounts
    __properties: ClassVar[List[str]] = ["attempts", "cached", "cost", "model", "provider", "request_hash", "response", "tokens"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GatewayOutcome from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response
        if self.response:
            _dict['response'] = self.response.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tokens
        if self.tokens:
            _dict['tokens'] = self.tokens.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GatewayOutcome from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attempts": obj.get("attempts"),
            "cached": obj.get("cached"),
            "cost": Money.from_dict(obj["cost"]) if obj.get("cost") is not None else None,
            "model": ModelRef.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "provider": obj.get("provider"),
            "request_hash": obj.get("request_hash"),
            "response": ChatCompletionResponse.from_dict(obj["response"]) if obj.get("response") is not None else None,
            "tokens": TokenCounts.from_dict(obj["tokens"]) if obj.get("tokens") is not None else None
        })
        return _obj


