# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from beater_client.models.chat_completion_request import ChatCompletionRequest
from beater_client.models.model_routing import ModelRouting
from typing import Optional, Set
from typing_extensions import Self

class GatewayChatHttpRequest(BaseModel):
    """
    Body for [`gateway_chat_completions_route`]: an OpenAI-compatible chat completion request plus the per-request routing policy and an optional budget ceiling. An empty `routing` means \"I did not bring a key\" — the gateway falls back to its managed default model if one is configured (hosted), otherwise it returns a typed no-key error (OSS).
    """ # noqa: E501
    budget_micros: Optional[StrictInt] = Field(default=None, description="Per-tenant budget ceiling in micros; defaults when omitted.")
    completion: ChatCompletionRequest = Field(description="The OpenAI-compatible chat completion request.")
    routing: Optional[List[ModelRouting]] = Field(default=None, description="Ordered failover list of credential policies (BYOK or managed).")
    __properties: ClassVar[List[str]] = ["budget_micros", "completion", "routing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GatewayChatHttpRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of completion
        if self.completion:
            _dict['completion'] = self.completion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in routing (list)
        _items = []
        if self.routing:
            for _item_routing in self.routing:
                if _item_routing:
                    _items.append(_item_routing.to_dict())
            _dict['routing'] = _items
        # set to None if budget_micros (nullable) is None
        # and model_fields_set contains the field
        if self.budget_micros is None and "budget_micros" in self.model_fields_set:
            _dict['budget_micros'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GatewayChatHttpRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "budget_micros": obj.get("budget_micros"),
            "completion": ChatCompletionRequest.from_dict(obj["completion"]) if obj.get("completion") is not None else None,
            "routing": [ModelRouting.from_dict(_item) for _item in obj["routing"]] if obj.get("routing") is not None else None
        })
        return _obj


