/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import ai.beater.client.model.ChatCompletionRequest;
import ai.beater.client.model.ModelRouting;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GatewayChatHttpRequest
 */
class GatewayChatHttpRequestTest {
    private final GatewayChatHttpRequest model = new GatewayChatHttpRequest();

    /**
     * Model tests for GatewayChatHttpRequest
     */
    @Test
    void testGatewayChatHttpRequest() {
        // TODO: test GatewayChatHttpRequest
    }

    /**
     * Test the property 'budgetMicros'
     */
    @Test
    void budgetMicrosTest() {
        // TODO: test budgetMicros
    }

    /**
     * Test the property 'completion'
     */
    @Test
    void completionTest() {
        // TODO: test completion
    }

    /**
     * Test the property 'routing'
     */
    @Test
    void routingTest() {
        // TODO: test routing
    }

}
