<?php
/**
 * TracesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Beater\Client\ApiException;
use Beater\Client\Configuration;
use Beater\Client\HeaderSelector;
use Beater\Client\ObjectSerializer;

/**
 * TracesApi Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TracesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getTrace' => [
            'application/json',
        ],
        'listTraces' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getTrace
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $trace_id trace_id (required)
     * @param  bool|null $unmask unmask (optional)
     * @param  string|null $reason reason (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrace'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Beater\Client\Model\TraceView|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse
     */
    public function getTrace($tenant_id, $trace_id, $unmask = null, $reason = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['getTrace'][0])
    {
        list($response) = $this->getTraceWithHttpInfo($tenant_id, $trace_id, $unmask, $reason, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);
        return $response;
    }

    /**
     * Operation getTraceWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $trace_id trace_id (required)
     * @param  bool|null $unmask (optional)
     * @param  string|null $reason (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrace'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Beater\Client\Model\TraceView|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTraceWithHttpInfo($tenant_id, $trace_id, $unmask = null, $reason = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['getTrace'][0])
    {
        $request = $this->getTraceRequest($tenant_id, $trace_id, $unmask, $reason, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Beater\Client\Model\TraceView' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\TraceView' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\TraceView', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Beater\Client\Model\TraceView';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\TraceView',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTraceAsync
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $trace_id trace_id (required)
     * @param  bool|null $unmask (optional)
     * @param  string|null $reason (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTraceAsync($tenant_id, $trace_id, $unmask = null, $reason = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['getTrace'][0])
    {
        return $this->getTraceAsyncWithHttpInfo($tenant_id, $trace_id, $unmask, $reason, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTraceAsyncWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $trace_id trace_id (required)
     * @param  bool|null $unmask (optional)
     * @param  string|null $reason (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTraceAsyncWithHttpInfo($tenant_id, $trace_id, $unmask = null, $reason = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['getTrace'][0])
    {
        $returnType = '\Beater\Client\Model\TraceView';
        $request = $this->getTraceRequest($tenant_id, $trace_id, $unmask, $reason, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTrace'
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $trace_id trace_id (required)
     * @param  bool|null $unmask (optional)
     * @param  string|null $reason (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTraceRequest($tenant_id, $trace_id, $unmask = null, $reason = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['getTrace'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling getTrace'
            );
        }

        // verify the required parameter 'trace_id' is set
        if ($trace_id === null || (is_array($trace_id) && count($trace_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $trace_id when calling getTrace'
            );
        }








        $resourcePath = '/v1/traces/{tenant_id}/{trace_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $unmask,
            'unmask', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reason,
            'reason', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($x_beater_api_key !== null) {
            $headerParams['x-beater-api-key'] = ObjectSerializer::toHeaderValue($x_beater_api_key);
        }
        // header params
        if ($x_beater_project_id !== null) {
            $headerParams['x-beater-project-id'] = ObjectSerializer::toHeaderValue($x_beater_project_id);
        }
        // header params
        if ($x_beater_environment_id !== null) {
            $headerParams['x-beater-environment-id'] = ObjectSerializer::toHeaderValue($x_beater_environment_id);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant_id' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($trace_id !== null) {
            $resourcePath = str_replace(
                '{' . 'trace_id' . '}',
                ObjectSerializer::toPathValue($trace_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listTraces
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string|null $project_id project_id (optional)
     * @param  string|null $environment_id environment_id (optional)
     * @param  string|null $trace_id trace_id (optional)
     * @param  string|null $kind kind (optional)
     * @param  string|null $status status (optional)
     * @param  string|null $started_after started_after (optional)
     * @param  string|null $started_before started_before (optional)
     * @param  string|null $model model (optional)
     * @param  string|null $release release (optional)
     * @param  int|null $min_cost_micros min_cost_micros (optional)
     * @param  int|null $max_cost_micros max_cost_micros (optional)
     * @param  int|null $min_latency_ms min_latency_ms (optional)
     * @param  int|null $max_latency_ms max_latency_ms (optional)
     * @param  int|null $limit limit (optional)
     * @param  string|null $cursor cursor (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTraces'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Beater\Client\Model\PageRunSummary|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse
     */
    public function listTraces($tenant_id, $project_id = null, $environment_id = null, $trace_id = null, $kind = null, $status = null, $started_after = null, $started_before = null, $model = null, $release = null, $min_cost_micros = null, $max_cost_micros = null, $min_latency_ms = null, $max_latency_ms = null, $limit = null, $cursor = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listTraces'][0])
    {
        list($response) = $this->listTracesWithHttpInfo($tenant_id, $project_id, $environment_id, $trace_id, $kind, $status, $started_after, $started_before, $model, $release, $min_cost_micros, $max_cost_micros, $min_latency_ms, $max_latency_ms, $limit, $cursor, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);
        return $response;
    }

    /**
     * Operation listTracesWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string|null $project_id (optional)
     * @param  string|null $environment_id (optional)
     * @param  string|null $trace_id (optional)
     * @param  string|null $kind (optional)
     * @param  string|null $status (optional)
     * @param  string|null $started_after (optional)
     * @param  string|null $started_before (optional)
     * @param  string|null $model (optional)
     * @param  string|null $release (optional)
     * @param  int|null $min_cost_micros (optional)
     * @param  int|null $max_cost_micros (optional)
     * @param  int|null $min_latency_ms (optional)
     * @param  int|null $max_latency_ms (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $cursor (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTraces'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Beater\Client\Model\PageRunSummary|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listTracesWithHttpInfo($tenant_id, $project_id = null, $environment_id = null, $trace_id = null, $kind = null, $status = null, $started_after = null, $started_before = null, $model = null, $release = null, $min_cost_micros = null, $max_cost_micros = null, $min_latency_ms = null, $max_latency_ms = null, $limit = null, $cursor = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listTraces'][0])
    {
        $request = $this->listTracesRequest($tenant_id, $project_id, $environment_id, $trace_id, $kind, $status, $started_after, $started_before, $model, $release, $min_cost_micros, $max_cost_micros, $min_latency_ms, $max_latency_ms, $limit, $cursor, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Beater\Client\Model\PageRunSummary' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\PageRunSummary' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\PageRunSummary', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Beater\Client\Model\PageRunSummary';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\PageRunSummary',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listTracesAsync
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string|null $project_id (optional)
     * @param  string|null $environment_id (optional)
     * @param  string|null $trace_id (optional)
     * @param  string|null $kind (optional)
     * @param  string|null $status (optional)
     * @param  string|null $started_after (optional)
     * @param  string|null $started_before (optional)
     * @param  string|null $model (optional)
     * @param  string|null $release (optional)
     * @param  int|null $min_cost_micros (optional)
     * @param  int|null $max_cost_micros (optional)
     * @param  int|null $min_latency_ms (optional)
     * @param  int|null $max_latency_ms (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $cursor (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTraces'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTracesAsync($tenant_id, $project_id = null, $environment_id = null, $trace_id = null, $kind = null, $status = null, $started_after = null, $started_before = null, $model = null, $release = null, $min_cost_micros = null, $max_cost_micros = null, $min_latency_ms = null, $max_latency_ms = null, $limit = null, $cursor = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listTraces'][0])
    {
        return $this->listTracesAsyncWithHttpInfo($tenant_id, $project_id, $environment_id, $trace_id, $kind, $status, $started_after, $started_before, $model, $release, $min_cost_micros, $max_cost_micros, $min_latency_ms, $max_latency_ms, $limit, $cursor, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listTracesAsyncWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string|null $project_id (optional)
     * @param  string|null $environment_id (optional)
     * @param  string|null $trace_id (optional)
     * @param  string|null $kind (optional)
     * @param  string|null $status (optional)
     * @param  string|null $started_after (optional)
     * @param  string|null $started_before (optional)
     * @param  string|null $model (optional)
     * @param  string|null $release (optional)
     * @param  int|null $min_cost_micros (optional)
     * @param  int|null $max_cost_micros (optional)
     * @param  int|null $min_latency_ms (optional)
     * @param  int|null $max_latency_ms (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $cursor (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTraces'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTracesAsyncWithHttpInfo($tenant_id, $project_id = null, $environment_id = null, $trace_id = null, $kind = null, $status = null, $started_after = null, $started_before = null, $model = null, $release = null, $min_cost_micros = null, $max_cost_micros = null, $min_latency_ms = null, $max_latency_ms = null, $limit = null, $cursor = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listTraces'][0])
    {
        $returnType = '\Beater\Client\Model\PageRunSummary';
        $request = $this->listTracesRequest($tenant_id, $project_id, $environment_id, $trace_id, $kind, $status, $started_after, $started_before, $model, $release, $min_cost_micros, $max_cost_micros, $min_latency_ms, $max_latency_ms, $limit, $cursor, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listTraces'
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string|null $project_id (optional)
     * @param  string|null $environment_id (optional)
     * @param  string|null $trace_id (optional)
     * @param  string|null $kind (optional)
     * @param  string|null $status (optional)
     * @param  string|null $started_after (optional)
     * @param  string|null $started_before (optional)
     * @param  string|null $model (optional)
     * @param  string|null $release (optional)
     * @param  int|null $min_cost_micros (optional)
     * @param  int|null $max_cost_micros (optional)
     * @param  int|null $min_latency_ms (optional)
     * @param  int|null $max_latency_ms (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $cursor (optional)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTraces'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listTracesRequest($tenant_id, $project_id = null, $environment_id = null, $trace_id = null, $kind = null, $status = null, $started_after = null, $started_before = null, $model = null, $release = null, $min_cost_micros = null, $max_cost_micros = null, $min_latency_ms = null, $max_latency_ms = null, $limit = null, $cursor = null, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listTraces'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling listTraces'
            );
        }














        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling TracesApi.listTraces, must be bigger than or equal to 0.');
        }







        $resourcePath = '/v1/traces/{tenant_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $environment_id,
            'environment_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $trace_id,
            'trace_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $kind,
            'kind', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $started_after,
            'started_after', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $started_before,
            'started_before', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $model,
            'model', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $release,
            'release', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $min_cost_micros,
            'min_cost_micros', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_cost_micros,
            'max_cost_micros', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $min_latency_ms,
            'min_latency_ms', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_latency_ms,
            'max_latency_ms', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($x_beater_api_key !== null) {
            $headerParams['x-beater-api-key'] = ObjectSerializer::toHeaderValue($x_beater_api_key);
        }
        // header params
        if ($x_beater_project_id !== null) {
            $headerParams['x-beater-project-id'] = ObjectSerializer::toHeaderValue($x_beater_project_id);
        }
        // header params
        if ($x_beater_environment_id !== null) {
            $headerParams['x-beater-environment-id'] = ObjectSerializer::toHeaderValue($x_beater_environment_id);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant_id' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
