/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayChatHttpRequest : Body for [`gateway_chat_completions_route`]: an OpenAI-compatible chat completion request plus the per-request routing policy and an optional budget ceiling. An empty `routing` means \"I did not bring a key\" — the gateway falls back to its managed default model if one is configured (hosted), otherwise it returns a typed no-key error (OSS).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayChatHttpRequest {
    /// Per-tenant budget ceiling in micros; defaults when omitted.
    #[serde(rename = "budget_micros", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub budget_micros: Option<Option<i64>>,
    /// The OpenAI-compatible chat completion request.
    #[serde(rename = "completion")]
    pub completion: Box<models::ChatCompletionRequest>,
    /// Ordered failover list of credential policies (BYOK or managed).
    #[serde(rename = "routing", skip_serializing_if = "Option::is_none")]
    pub routing: Option<Vec<models::ModelRouting>>,
}

impl GatewayChatHttpRequest {
    /// Body for [`gateway_chat_completions_route`]: an OpenAI-compatible chat completion request plus the per-request routing policy and an optional budget ceiling. An empty `routing` means \"I did not bring a key\" — the gateway falls back to its managed default model if one is configured (hosted), otherwise it returns a typed no-key error (OSS).
    pub fn new(completion: models::ChatCompletionRequest) -> GatewayChatHttpRequest {
        GatewayChatHttpRequest {
            budget_micros: None,
            completion: Box::new(completion),
            routing: None,
        }
    }
}

