/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelRoutingOneOf : Bring-your-own-key: resolve the tenant's opaque provider secret.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelRoutingOneOf {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "provider_secret_id")]
    pub provider_secret_id: String,
}

impl ModelRoutingOneOf {
    /// Bring-your-own-key: resolve the tenant's opaque provider secret.
    pub fn new(kind: Kind, provider_secret_id: String) -> ModelRoutingOneOf {
        ModelRoutingOneOf {
            kind,
            provider_secret_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "byok")]
    Byok,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Byok
    }
}

