/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelRoutingOneOf1 : Use the managed default model (hosted only).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelRoutingOneOf1 {
    #[serde(rename = "default_model")]
    pub default_model: Box<models::ModelRef>,
    #[serde(rename = "kind")]
    pub kind: Kind,
}

impl ModelRoutingOneOf1 {
    /// Use the managed default model (hosted only).
    pub fn new(default_model: models::ModelRef, kind: Kind) -> ModelRoutingOneOf1 {
        ModelRoutingOneOf1 {
            default_model: Box::new(default_model),
            kind,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "managed")]
    Managed,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Managed
    }
}

