/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/GatewayChatHttpRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GatewayChatHttpRequest::GatewayChatHttpRequest()
{
    m_Budget_micros = 0L;
    m_Budget_microsIsSet = false;
    m_CompletionIsSet = false;
    m_RoutingIsSet = false;
}

GatewayChatHttpRequest::~GatewayChatHttpRequest()
{
}

void GatewayChatHttpRequest::validate()
{
    // TODO: implement validation
}

web::json::value GatewayChatHttpRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Budget_microsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("budget_micros"))] = ModelBase::toJson(m_Budget_micros);
    }
    if(m_CompletionIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("completion"))] = ModelBase::toJson(m_Completion);
    }
    if(m_RoutingIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("routing"))] = ModelBase::toJson(m_Routing);
    }

    return val;
}

bool GatewayChatHttpRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("budget_micros"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("budget_micros")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setBudgetMicros;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBudgetMicros);
            setBudgetMicros(refVal_setBudgetMicros);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("completion"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("completion")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ChatCompletionRequest> refVal_setCompletion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompletion);
            setCompletion(refVal_setCompletion);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("routing"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("routing")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ModelRouting>> refVal_setRouting;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRouting);
            setRouting(refVal_setRouting);
            
        }
    }
    return ok;
}

void GatewayChatHttpRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Budget_microsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("budget_micros")), m_Budget_micros));
    }
    if(m_CompletionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("completion")), m_Completion));
    }
    if(m_RoutingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("routing")), m_Routing));
    }
}

bool GatewayChatHttpRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("budget_micros"))))
    {
        int64_t refVal_setBudgetMicros;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("budget_micros"))), refVal_setBudgetMicros );
        setBudgetMicros(refVal_setBudgetMicros);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("completion"))))
    {
        std::shared_ptr<ChatCompletionRequest> refVal_setCompletion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("completion"))), refVal_setCompletion );
        setCompletion(refVal_setCompletion);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("routing"))))
    {
        std::vector<std::shared_ptr<ModelRouting>> refVal_setRouting;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("routing"))), refVal_setRouting );
        setRouting(refVal_setRouting);
    }
    return ok;
}


int64_t GatewayChatHttpRequest::getBudgetMicros() const
{
    return m_Budget_micros;
}

void GatewayChatHttpRequest::setBudgetMicros(int64_t value)
{
    m_Budget_micros = value;
    m_Budget_microsIsSet = true;
}

bool GatewayChatHttpRequest::budgetMicrosIsSet() const
{
    return m_Budget_microsIsSet;
}

void GatewayChatHttpRequest::unsetBudget_micros()
{
    m_Budget_microsIsSet = false;
}
std::shared_ptr<ChatCompletionRequest> GatewayChatHttpRequest::getCompletion() const
{
    return m_Completion;
}


void GatewayChatHttpRequest::setCompletion(const std::shared_ptr<ChatCompletionRequest>& value)
{
    m_Completion = value;
    m_CompletionIsSet = true;
}

bool GatewayChatHttpRequest::completionIsSet() const
{
    return m_CompletionIsSet;
}

void GatewayChatHttpRequest::unsetCompletion()
{
    m_CompletionIsSet = false;
}
std::vector<std::shared_ptr<ModelRouting>> GatewayChatHttpRequest::getRouting() const
{
    return m_Routing;
}


void GatewayChatHttpRequest::setRouting(const std::vector<std::shared_ptr<ModelRouting>>& value)
{
    m_Routing = value;
    m_RoutingIsSet = true;
}

bool GatewayChatHttpRequest::routingIsSet() const
{
    return m_RoutingIsSet;
}

void GatewayChatHttpRequest::unsetRouting()
{
    m_RoutingIsSet = false;
}

}
}
}
}


