/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.beater.client.model.ChatMessage;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.beater.client.ApiClient;
/**
 * An OpenAI-compatible chat completion request. The &#x60;model&#x60; field is a free-form model identifier, making the gateway model-agnostic: any provider/model can be named per request, paired with a [&#x60;ModelRouting&#x60;] credential policy.
 */
@JsonPropertyOrder({
  ChatCompletionRequest.JSON_PROPERTY_MAX_TOKENS,
  ChatCompletionRequest.JSON_PROPERTY_MESSAGES,
  ChatCompletionRequest.JSON_PROPERTY_MODEL,
  ChatCompletionRequest.JSON_PROPERTY_REASONING_EFFORT,
  ChatCompletionRequest.JSON_PROPERTY_TEMPERATURE,
  ChatCompletionRequest.JSON_PROPERTY_TOP_P
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class ChatCompletionRequest {
  public static final String JSON_PROPERTY_MAX_TOKENS = "max_tokens";
  private JsonNullable<Long> maxTokens = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @javax.annotation.Nonnull
  private List<ChatMessage> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  public static final String JSON_PROPERTY_REASONING_EFFORT = "reasoning_effort";
  private JsonNullable<String> reasoningEffort = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  private JsonNullable<Double> temperature = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_TOP_P = "top_p";
  private JsonNullable<Double> topP = JsonNullable.<Double>undefined();

  public ChatCompletionRequest() { 
  }

  public ChatCompletionRequest maxTokens(@javax.annotation.Nullable Long maxTokens) {
    this.maxTokens = JsonNullable.<Long>of(maxTokens);
    return this;
  }

  /**
   * Get maxTokens
   * minimum: 0
   * @return maxTokens
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Long getMaxTokens() {
        return maxTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MAX_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getMaxTokens_JsonNullable() {
    return maxTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_MAX_TOKENS)
  public void setMaxTokens_JsonNullable(JsonNullable<Long> maxTokens) {
    this.maxTokens = maxTokens;
  }

  public void setMaxTokens(@javax.annotation.Nullable Long maxTokens) {
    this.maxTokens = JsonNullable.<Long>of(maxTokens);
  }


  public ChatCompletionRequest messages(@javax.annotation.Nonnull List<ChatMessage> messages) {
    this.messages = messages;
    return this;
  }

  public ChatCompletionRequest addMessagesItem(ChatMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ChatMessage> getMessages() {
    return messages;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@javax.annotation.Nonnull List<ChatMessage> messages) {
    this.messages = messages;
  }


  public ChatCompletionRequest model(@javax.annotation.Nonnull String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }


  public ChatCompletionRequest reasoningEffort(@javax.annotation.Nullable String reasoningEffort) {
    this.reasoningEffort = JsonNullable.<String>of(reasoningEffort);
    return this;
  }

  /**
   * OpenAI-style reasoning effort hint (&#x60;low&#x60; | &#x60;medium&#x60; | &#x60;high&#x60;), forwarded to providers that understand it.
   * @return reasoningEffort
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getReasoningEffort() {
        return reasoningEffort.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REASONING_EFFORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReasoningEffort_JsonNullable() {
    return reasoningEffort;
  }
  
  @JsonProperty(JSON_PROPERTY_REASONING_EFFORT)
  public void setReasoningEffort_JsonNullable(JsonNullable<String> reasoningEffort) {
    this.reasoningEffort = reasoningEffort;
  }

  public void setReasoningEffort(@javax.annotation.Nullable String reasoningEffort) {
    this.reasoningEffort = JsonNullable.<String>of(reasoningEffort);
  }


  public ChatCompletionRequest temperature(@javax.annotation.Nullable Double temperature) {
    this.temperature = JsonNullable.<Double>of(temperature);
    return this;
  }

  /**
   * Get temperature
   * @return temperature
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Double getTemperature() {
        return temperature.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getTemperature_JsonNullable() {
    return temperature;
  }
  
  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  public void setTemperature_JsonNullable(JsonNullable<Double> temperature) {
    this.temperature = temperature;
  }

  public void setTemperature(@javax.annotation.Nullable Double temperature) {
    this.temperature = JsonNullable.<Double>of(temperature);
  }


  public ChatCompletionRequest topP(@javax.annotation.Nullable Double topP) {
    this.topP = JsonNullable.<Double>of(topP);
    return this;
  }

  /**
   * Get topP
   * @return topP
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Double getTopP() {
        return topP.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOP_P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getTopP_JsonNullable() {
    return topP;
  }
  
  @JsonProperty(JSON_PROPERTY_TOP_P)
  public void setTopP_JsonNullable(JsonNullable<Double> topP) {
    this.topP = topP;
  }

  public void setTopP(@javax.annotation.Nullable Double topP) {
    this.topP = JsonNullable.<Double>of(topP);
  }


  /**
   * Return true if this ChatCompletionRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequest chatCompletionRequest = (ChatCompletionRequest) o;
    return equalsNullable(this.maxTokens, chatCompletionRequest.maxTokens) &&
        Objects.equals(this.messages, chatCompletionRequest.messages) &&
        Objects.equals(this.model, chatCompletionRequest.model) &&
        equalsNullable(this.reasoningEffort, chatCompletionRequest.reasoningEffort) &&
        equalsNullable(this.temperature, chatCompletionRequest.temperature) &&
        equalsNullable(this.topP, chatCompletionRequest.topP);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(maxTokens), messages, model, hashCodeNullable(reasoningEffort), hashCodeNullable(temperature), hashCodeNullable(topP));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequest {\n");
    sb.append("    maxTokens: ").append(toIndentedString(maxTokens)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    reasoningEffort: ").append(toIndentedString(reasoningEffort)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `max_tokens` to the URL query string
    if (getMaxTokens() != null) {
      joiner.add(String.format("%smax_tokens%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaxTokens()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `messages` to the URL query string
    if (getMessages() != null) {
      for (int i = 0; i < getMessages().size(); i++) {
        if (getMessages().get(i) != null) {
          joiner.add(getMessages().get(i).toUrlQueryString(String.format("%smessages%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(String.format("%smodel%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getModel()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `reasoning_effort` to the URL query string
    if (getReasoningEffort() != null) {
      joiner.add(String.format("%sreasoning_effort%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getReasoningEffort()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `temperature` to the URL query string
    if (getTemperature() != null) {
      joiner.add(String.format("%stemperature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTemperature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `top_p` to the URL query string
    if (getTopP() != null) {
      joiner.add(String.format("%stop_p%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTopP()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

