/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.beater.client.model.ChatCompletionResponse;
import ai.beater.client.model.ModelRef;
import ai.beater.client.model.Money;
import ai.beater.client.model.TokenCounts;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.beater.client.ApiClient;
/**
 * The result of a successfully proxied completion.
 */
@JsonPropertyOrder({
  GatewayOutcome.JSON_PROPERTY_ATTEMPTS,
  GatewayOutcome.JSON_PROPERTY_CACHED,
  GatewayOutcome.JSON_PROPERTY_COST,
  GatewayOutcome.JSON_PROPERTY_MODEL,
  GatewayOutcome.JSON_PROPERTY_PROVIDER,
  GatewayOutcome.JSON_PROPERTY_REQUEST_HASH,
  GatewayOutcome.JSON_PROPERTY_RESPONSE,
  GatewayOutcome.JSON_PROPERTY_TOKENS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GatewayOutcome {
  public static final String JSON_PROPERTY_ATTEMPTS = "attempts";
  @javax.annotation.Nonnull
  private Integer attempts;

  public static final String JSON_PROPERTY_CACHED = "cached";
  @javax.annotation.Nonnull
  private Boolean cached;

  public static final String JSON_PROPERTY_COST = "cost";
  @javax.annotation.Nonnull
  private Money cost;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private ModelRef model;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nonnull
  private String provider;

  public static final String JSON_PROPERTY_REQUEST_HASH = "request_hash";
  @javax.annotation.Nonnull
  private String requestHash;

  public static final String JSON_PROPERTY_RESPONSE = "response";
  @javax.annotation.Nonnull
  private ChatCompletionResponse response;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @javax.annotation.Nonnull
  private TokenCounts tokens;

  public GatewayOutcome() { 
  }

  public GatewayOutcome attempts(@javax.annotation.Nonnull Integer attempts) {
    this.attempts = attempts;
    return this;
  }

  /**
   * Get attempts
   * minimum: 0
   * @return attempts
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTEMPTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAttempts() {
    return attempts;
  }


  @JsonProperty(JSON_PROPERTY_ATTEMPTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttempts(@javax.annotation.Nonnull Integer attempts) {
    this.attempts = attempts;
  }


  public GatewayOutcome cached(@javax.annotation.Nonnull Boolean cached) {
    this.cached = cached;
    return this;
  }

  /**
   * Get cached
   * @return cached
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CACHED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getCached() {
    return cached;
  }


  @JsonProperty(JSON_PROPERTY_CACHED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCached(@javax.annotation.Nonnull Boolean cached) {
    this.cached = cached;
  }


  public GatewayOutcome cost(@javax.annotation.Nonnull Money cost) {
    this.cost = cost;
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Money getCost() {
    return cost;
  }


  @JsonProperty(JSON_PROPERTY_COST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCost(@javax.annotation.Nonnull Money cost) {
    this.cost = cost;
  }


  public GatewayOutcome model(@javax.annotation.Nonnull ModelRef model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelRef getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull ModelRef model) {
    this.model = model;
  }


  public GatewayOutcome provider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
  }


  public GatewayOutcome requestHash(@javax.annotation.Nonnull String requestHash) {
    this.requestHash = requestHash;
    return this;
  }

  /**
   * Get requestHash
   * @return requestHash
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUEST_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestHash() {
    return requestHash;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestHash(@javax.annotation.Nonnull String requestHash) {
    this.requestHash = requestHash;
  }


  public GatewayOutcome response(@javax.annotation.Nonnull ChatCompletionResponse response) {
    this.response = response;
    return this;
  }

  /**
   * Get response
   * @return response
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ChatCompletionResponse getResponse() {
    return response;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponse(@javax.annotation.Nonnull ChatCompletionResponse response) {
    this.response = response;
  }


  public GatewayOutcome tokens(@javax.annotation.Nonnull TokenCounts tokens) {
    this.tokens = tokens;
    return this;
  }

  /**
   * Get tokens
   * @return tokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TokenCounts getTokens() {
    return tokens;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokens(@javax.annotation.Nonnull TokenCounts tokens) {
    this.tokens = tokens;
  }


  /**
   * Return true if this GatewayOutcome object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GatewayOutcome gatewayOutcome = (GatewayOutcome) o;
    return Objects.equals(this.attempts, gatewayOutcome.attempts) &&
        Objects.equals(this.cached, gatewayOutcome.cached) &&
        Objects.equals(this.cost, gatewayOutcome.cost) &&
        Objects.equals(this.model, gatewayOutcome.model) &&
        Objects.equals(this.provider, gatewayOutcome.provider) &&
        Objects.equals(this.requestHash, gatewayOutcome.requestHash) &&
        Objects.equals(this.response, gatewayOutcome.response) &&
        Objects.equals(this.tokens, gatewayOutcome.tokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attempts, cached, cost, model, provider, requestHash, response, tokens);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GatewayOutcome {\n");
    sb.append("    attempts: ").append(toIndentedString(attempts)).append("\n");
    sb.append("    cached: ").append(toIndentedString(cached)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    requestHash: ").append(toIndentedString(requestHash)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `attempts` to the URL query string
    if (getAttempts() != null) {
      joiner.add(String.format("%sattempts%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAttempts()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `cached` to the URL query string
    if (getCached() != null) {
      joiner.add(String.format("%scached%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCached()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `cost` to the URL query string
    if (getCost() != null) {
      joiner.add(getCost().toUrlQueryString(prefix + "cost" + suffix));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(getModel().toUrlQueryString(prefix + "model" + suffix));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format("%sprovider%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getProvider()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `request_hash` to the URL query string
    if (getRequestHash() != null) {
      joiner.add(String.format("%srequest_hash%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRequestHash()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `response` to the URL query string
    if (getResponse() != null) {
      joiner.add(getResponse().toUrlQueryString(prefix + "response" + suffix));
    }

    // add `tokens` to the URL query string
    if (getTokens() != null) {
      joiner.add(getTokens().toUrlQueryString(prefix + "tokens" + suffix));
    }

    return joiner.toString();
  }
}

