/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ChatCompletionUsage.h
 *
 * Token usage in the OpenAI-compatible response shape.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ChatCompletionUsage_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ChatCompletionUsage_H_


#include "beater-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Token usage in the OpenAI-compatible response shape.
/// </summary>
class  ChatCompletionUsage
    : public ModelBase
{
public:
    ChatCompletionUsage();
    virtual ~ChatCompletionUsage();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ChatCompletionUsage members


    int64_t getCompletionTokens() const;
    bool completionTokensIsSet() const;
    void unsetCompletion_tokens();
    void setCompletionTokens(int64_t value);

    int64_t getPromptTokens() const;
    bool promptTokensIsSet() const;
    void unsetPrompt_tokens();
    void setPromptTokens(int64_t value);

    int64_t getTotalTokens() const;
    bool totalTokensIsSet() const;
    void unsetTotal_tokens();
    void setTotalTokens(int64_t value);


protected:
    int64_t m_Completion_tokens;
    bool m_Completion_tokensIsSet;

    int64_t m_Prompt_tokens;
    bool m_Prompt_tokensIsSet;

    int64_t m_Total_tokens;
    bool m_Total_tokensIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ChatCompletionUsage_H_ */
